### ISSUE TITLE
Unable To use the program , nothing appears but the gold graph background (no infos though) [BUG]

### ISSUE THREAD

**Issue by crashbach** [floh22/LeagueBroadcastHub#10]
Hello.

i just downloaded league broadcast hub and leagueOCR but i get no infos and i have no idea how to work with it , would u please help me out , i only get the gold grap[h background and thats about it.

Thank you for your time.

**Comment by floh22** [comment]
LeagueOCR has been deprecated in favor of using memory reading for quite some time now.

Download the [latest release](https://github.com/floh22/LeagueBroadcastHub/releases/latest)

If you have any further issues, please use the issue templates so I can best help you

**Comment by crashbach** [comment]
I still haven't figured it out and now when i click on goldgraph the program crashes , but still i dont think and doing it the right way , i see people posting screens of consoles and whatnot and i have no idea how to use that , is cloud needed to run the program if not how do i access the console like other people.
thank you so much for your time.

**Comment by floh22** [comment]
The program generates logs and crash logs which can be found in the folder Logs. Post both of them if the program crahses, or just the log if it does not crash

**Comment by crashbach** [comment]
Again thank you for your time , here are both the crash logs 
[Crash-2021-05-27-01-21.log](https://github.com/floh22/LeagueBroadcastHub/files/6555954/Crash-2021-05-27-01-21.log)
and the program logs 
[Log-2021-05-27-01-20.log](https://github.com/floh22/LeagueBroadcastHub/files/6555958/Log-2021-05-27-01-20.log)

**Comment by floh22** [comment]
It looks like neither LiveEvents, GitHub connection, or Memory Reading are working.
Im going to add more logging in a future update and hope I can find the issue then.

Im sorry to say, but for now it looks like somehow everything broke at the same time
