### ISSUE TITLE
How can I add my own font？

### ISSUE THREAD

**Issue by Khhd1** [floh22/LeagueBroadcastHub#100]
I want to use my own font in some places

**Comment by shinilee** [comment]
1. lol-pick-ban-ui-master\lol-pick-ban-ui-master\layouts\layout-volu-europe\src\assets\fonts
put your desire font in that folder

2. lol-pick-ban-ui-master\lol-pick-ban-ui-master\layouts\layout-volu-europe\src\europe\style
open the font.less and edit src: url("../../assets/fonts/amarurgt.ttf"); amarurgt.ttf the font name to your desire font name

3. open the index.less change the .Patch Font-Size 25px to your desire font size

**Comment by Khhd1** [comment]
> 
Oh! Thank you. I successfully solved the problem!

**Comment by shinilee** [comment]
I'm sorry I though I was in  lol-pick-ban-ui

I believe you can't use your own font for leaguebriadcast program yet you only can use google font I think

you can change in

![image](https://user-images.githubusercontent.com/82671596/146646176-bb0d2159-014f-4c1e-a9e7-bc6dfefd8b00.png)

ingame.json file

**Comment by Khhd1** [comment]
> I'm sorry I though I was in lol-pick-ban-ui
> 
> I believe you can't use your own font for leaguebriadcast program yet you only can use google font I think
> 
> you can change in
> 
> ![image](https://user-images.githubusercontent.com/82671596/146646176-bb0d2159-014f-4c1e-a9e7-bc6dfefd8b00.png)
> 
> ingame.json file

Oh, thank you, buddy. I changed the font.
