### ISSUE TITLE
[BUG] Text positioning and Gold not reading

### ISSUE THREAD

**Issue by UnifiedHyper** [floh22/LeagueBroadcastHub#101]
**Describe the bug**
I've encountered two errors. The first is that the program is not reading/tracking gold no matter what's happening.
The second is that the kills text is not properly positioning/aligning, and the red and blue kills are even aligning differently with identically opposite positions and alignment.

[Log-2021-12-17-13-07.log](https://github.com/floh22/LeagueBroadcast/files/7737311/Log-2021-12-17-13-07.log)
![Screenshot (94)](https://user-images.githubusercontent.com/94020233/146596274-2834b1a5-b139-4d87-8c84-0bbabb70e546.png)
![Screenshot (95)](https://user-images.githubusercontent.com/94020233/146596484-9a03efab-bc1b-44e2-b9c9-8aab68b66bca.png)
![Screenshot (96)](https://user-images.githubusercontent.com/94020233/146596485-025e6b71-8647-4fb4-8a3f-a1dbf175c74d.png)

**Comment by shinilee** [comment]
gold not reading is the offsets problem simple fix but I have no idea how to find current offsets....

**Comment by floh22** [comment]
Text positions are going to be a bit wonky since the entire project lacks polish atm. For now, update the value, save the file, and use trial and error to fix the position.

As for the Gold not reading, delete Farsight.json and restart the program. Riot changed internal structures and I did not notice, leading to me publishing incorrect offsets.

**Comment by shinilee** [comment]
> Text positions are going to be a bit wonky since the entire project lacks polish atm. For now, update the value, save the file, and use trial and error to fix the position.
> 
> As for the Gold not reading, delete Farsight.json and restart the program. Riot changed internal structures and I did not notice, leading to me publishing incorrect offsets.

I have question for the future if this happen again do I need to wait until you fix the value? or I can just delete the Farsight.json and restart the program it will fix?

**Comment by UnifiedHyper** [comment]
> Text positions are going to be a bit wonky since the entire project lacks polish atm. For now, update the value, save the file, and use trial and error to fix the position.
> 
> As for the Gold not reading, delete Farsight.json and restart the program. Riot changed internal structures and I did not notice, leading to me publishing incorrect offsets.

So for the text, it will actually sometimes CHANGE after restarting the program. Like it will move from where I set it for some reason. Is there a way to address this?
