### ISSUE TITLE
[BUG] Gold not counting, with a memory issue posted

### ISSUE THREAD

**Issue by Megge-k** [floh22/LeagueBroadcastHub#102]
No crash log as cs/min still works, kills still count + drakes. But counting gold at the top part of the scoreboard is not adding up past 2,5k vs 2,5k. Gold graph and gold per player is not working. Nor those item popup.

Included the log.

[Log-2021-12-19-16-02.txt](https://github.com/floh22/LeagueBroadcast/files/7741165/Log-2021-12-19-16-02.txt)

**Comment by shinilee** [comment]
yup not working for me too

**Comment by floh22** [comment]
Try to delete Farsight.json and have it redownload. I just checked the memory values again, and they work for me EUW. AFAIK all Riot regions are on the same patch currently, so they should be the same for you. Make sure Farsight.json has `"Manager": "0x186CD64"`

**Comment by shinilee** [comment]
just tried it and it work thank you~
