### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Danglo23** [floh22/LeagueBroadcastHub#104]
I may be a complete idiot but I can't make it work. I really don't understand what I need to do. I get to open the app and set up what I want. But then nothing happens. I've added the links to OBS too, any help? Maybe a "for dummies" step by step? 
Much appreciated

**Comment by TheDeathLotus** [comment]
Same here, though it's probably needed to say I have very little to no experience with GitHub and FrontEnd. Got the LeagueBroadcast-1.4.106.zip downloaded, set up and everything set-up inside of the app, with Streamlabs OBS paired up as well. The app itself says that the Client is connected though it doesn't create any sort of overlay for me when I jump into Drafting phase or the Game (where it straight up says the client is disconnected while ingame)

**Comment by jfenn3883** [comment]
I am having the same issue with the application saying disconnected with in game
