### ISSUE TITLE
[QUESTION] How to change the POSITION of the scoreboard popup events?

### ISSUE THREAD

**Issue by xTuCo** [floh22/LeagueBroadcastHub#106]
Hi all,

Someone could help me about **changing the position of the scoreboard popup** when you kill an objective or it spawns (drake, baron, herald)?

I don't see any line related to this in the **Config.json** file...

Some help?

Thanks!

**Comment by FireFoXz09** [comment]
It's mostly a mask over the full animation at the bottom of the screen. I've not tried to move it like at the top of the screen or something like it tho. Modify the mask (png image) to change how small or big it will appear. (I dunno if this helps)

**Comment by xTuCo** [comment]
> It's mostly a mask over the full animation at the bottom of the screen. I've not tried to move it like at the top of the screen or something like it tho. Modify the mask (png image) to change how small or big it will appear. (I dunno if this helps)

I meant how to move the whole animation, not only the mask where the objective icon appears. Do you know how I could to that? Thanks for your answers!

**Comment by FireFoXz09** [comment]
No sorry I don't know how to move it. We mostly keep it on the bottom part of the screen since it won't hinder any view of the game this way (and most pro league do the same).

**Comment by floh22** [comment]
best way would probably be to change the mask to the size of the screen, and then have the mask transparent only where you want it to show. The animation still comes in from the bottom, that cant be changed in config as far as I remember. You would have to change the frontend code and build it yourself
