### ISSUE TITLE
[BUG] Custom backgrounds and images doesn't show up

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#115]
Hello, I have customized the backgrounds for all windows. However, this only appears for some and not others. And, that of the Gold graphs appears after several seconds or even sometimes gives me the old one. For inhibitors it does not even appear. I have to reload the overlay every time and again, it doesn't work every time, whereas when, they are the originals overlays, this problem does not arise.

![dfxdfsdxfsdfsdf](https://user-images.githubusercontent.com/82313405/150622505-a8c5cdf1-afc1-4b31-87d2-8ba4abfeb7fd.png)

Small precision, the bug of the timers of the inhinitors, only occurs on OBS. When you open the link in a browser (Chrome for example) the image appears in the right place... I didnt understand why in OBS that happened.

And how we can change the text for stats ? "EXP PER PLAYER" "PLAYER GOLD"  etc... I didnt found the file for changer this on my language.

Thx and good job again ! :D

**Comment by AzureAstral** [comment]
https://user-images.githubusercontent.com/82313405/150623249-8c9b2329-84dd-4f32-89fe-8d82f660e743.mp4

New bug too ! :)

**Comment by daisukedd** [comment]
Disable alpha and refresh appliccation  and web broser with .json

**Comment by AzureAstral** [comment]
> Disable alpha and refresh appliccation and web broser with .json

atm i have this for gold graph : 

    "Background": {
      "UseImage": true,
      "UseVideo": false,
      "UseAlpha": false,
      "FallbackColor": "rgba(19,24,63,255)"

And it's didnt work :(

**Comment by exr** [comment]
Did you find a solution to that problem @AzureAstral? Having the same right now

Also: is there no "test mode" which shows all available overlays right now? It's pretty difficult working on those graphics and always having the game running as spectator

**Comment by AzureAstral** [comment]
No solution… Same problem :(

**Comment by JoanJuan10** [comment]
Okay so I was having the same problem and I found something that might help fix this issue. It seems the background of the gold graph reloads at the same time someone gets an item. I suppose that when it shows up, all overlays are reloaded and fixes the issue until you hide the gold graph, after that it bugs again. It's a loop.

https://user-images.githubusercontent.com/37046841/155891153-030ee44a-2e01-445c-a828-885a57276b14.mp4
