### ISSUE TITLE
[BUG] CRASH WHEN I START THE GAME

### ISSUE THREAD

**Issue by saexy** [floh22/LeagueBroadcastHub#118]
When i start the game, LeagueBroadcast crashs

 - OS: [e.g. Windows 10]
 - Version 1909

**Comment by Coow** [comment]
AFAIK the Windows Version is too old. Could you attach a Crash Report?
Its located here LeagueBroadcast\Logs\CrashLogs, then the file with the timestamp of the crash

**Comment by TKRZHAI** [comment]
I have the same issue
[Log-2022-02-15-14-42.log](https://github.com/floh22/LeagueBroadcast/files/8075217/Log-2022-02-15-14-42.log)

**Comment by Coow** [comment]
> 

[14-42-15] [WARNING] App Crash detected. Writing Crash report to CrashLogs\Crash-2022-02-15-14-42.log
Could you send the crashlog instead please?

**Comment by TKRZHAI** [comment]
here we g
[Crash-2022-02-15-14-42.log](https://github.com/floh22/LeagueBroadcast/files/8075254/Crash-2022-02-15-14-42.log)
o

**Comment by floh22** [comment]
Looks like a corrupted config. Try deleting farsight.json
