### ISSUE TITLE
[BUG] CS per Min. and Gold Tab 

### ISSUE THREAD

**Issue by lolThinked** [floh22/LeagueBroadcastHub#12]
**Describe the bug**
Both CS per Min and Gold shows some wierd numbers and have some wierd formatting.

**To Reproduce**

**Expected behavior**

**Material**
![image](https://user-images.githubusercontent.com/48737270/119831134-434c2880-befd-11eb-868b-1b075240a4ea.png)
![image](https://user-images.githubusercontent.com/48737270/119831210-55c66200-befd-11eb-8b2f-5b5b7dd04ad0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**
Riot games disabled [LiveEvent] as of yesterday, using port34243.

**Comment by OrionCodeDev** [comment]
Hey, hm i tested  942039c, but i have still that bug. Best Regards
![sS32dHa](https://user-images.githubusercontent.com/47286873/119909267-c482da00-bf54-11eb-8e76-6b0b4c11652b.png)
![QY4L306](https://user-images.githubusercontent.com/47286873/119909268-c5b40700-bf54-11eb-8172-f073b09eaa26.png)
