### ISSUE TITLE
[SUPPORT] Setup the app locally

### ISSUE THREAD

**Issue by Alex-Tsvetanov** [floh22/LeagueBroadcastHub#120]
Hello,
I have issues starting ``http://localhost:9001/frontend?backend=localhost`` locally after ``Start without Debugging`` via Visual Studio 2022.

Can you give some instructions or message so we can arrange 1on1 help?

Regards,
Alex

**Comment by floh22** [comment]
Make sure to add the Frontend folder to your debug run environment, it does not get copied over automatically.

Structure would be something like `Debug/Frontend/ingame` and `Debug/Frontend/pickban` each with the built versions of the website.

Either that or start dev environments of the websites yourself. They are in Overlays/ and then their respective folder. Each has their own readme on this git
