### ISSUE TITLE
[FEATURE] Support new language

### ISSUE THREAD

**Issue by hmcdat** [floh22/LeagueBroadcastHub#121]
Hello, I am from Vietnam.
Can you support Vietnamese language in this toolkit?
Thank you xD

**Comment by floh22** [comment]
Something that may come in the future.
If you wish to change item names in the overlay, you can change that manually by changing DataDragon: Locale to `vn_VN`. All supported language codes are included in this file: https://ddragon.leagueoflegends.com/cdn/languages.json
