### ISSUE TITLE
[BUG] Program crashes upon loading into a custom game

### ISSUE THREAD

**Issue by Hay1tsme** [floh22/LeagueBroadcastHub#122]
**Describe the bug**
After the loading screen when loading into a custom game, LeagueHub will quietly crash

**Material**
Log: 
[Crash-2022-02-18-21-16.log](https://github.com/floh22/LeagueBroadcast/files/8101343/Crash-2022-02-18-21-16.log)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 20H2

**Comment by floh22** [comment]
Was this a spectate game or was it played directly?

**Comment by Hay1tsme** [comment]
It was being spectated. The crash seems to be inconsistent, as spectating non-private games always works without issue, and spectating private lobby games seems to have about a 50/50 chance to crash.
