### ISSUE TITLE
[BUG] No Champion Icons in Exp tab and similar

### ISSUE THREAD

**Issue by Flofian** [floh22/LeagueBroadcastHub#123]
Opening the Exp tab shows the data and the summoner name they belong to, but no champion icon in most cases. It happend to me that there were a few icons, but I have no log file or any more infos of that.
New installation and restarting didnt help.

Attached are a verbose log file and a screenshot of the problem
[Log-2022-02-20-14-27.log](https://github.com/floh22/LeagueBroadcast/files/8104094/Log-2022-02-20-14-27.log)
![screenshot](https://user-images.githubusercontent.com/56082272/154845754-e4b07d38-e995-4c30-a514-9d1c8794c750.png)

**Comment by floh22** [comment]
Can you open the overlay website in your browser and check if the same happens there?
You can open the console in your browser and check for any errors there.
If any errors appear, can you post them as well?
