### ISSUE TITLE
[BUG] [LOW PRIO] Scoreboard only shows kills that happened in the current "session"

### ISSUE THREAD

**Issue by Flofian** [floh22/LeagueBroadcastHub#124]
If you open a replay mid game, it only counts the kills that happened since the start of this "replay file". 

Attached are 2 screenshots, the first show the external overlay, the second one shows the ingame score.
You can see the kills that happened at the ingame timeline.
![screenshot1](https://user-images.githubusercontent.com/56082272/154846119-99f847ac-481f-4c69-8ded-517be22d69ca.png)
![screenshot2](https://user-images.githubusercontent.com/56082272/154846125-ec00470c-3fe3-4ee9-8db2-74e76057ec3e.png)

For general purposes, here's a verbose log file where it happened
[Log-2022-02-20-14-27.log](https://github.com/floh22/LeagueBroadcast/files/8104127/Log-2022-02-20-14-27.log)

**Comment by floh22** [comment]
Limitation of memory reading
