### ISSUE TITLE
[FEATURE] / [BUG] The external scoreboard no longer covers the entire ingame scoreboard

### ISSUE THREAD

**Issue by Flofian** [floh22/LeagueBroadcastHub#125]
Since the addion of Objective Bounties (I think), the external scoreboard no longer fully covers the ingame one and also doesnt provide as much information as the ingame one.

A few Ideas:

- Make it easier for the user to customize things (maybe it's already possible, but I couldn't find anything)
- Simply extend the external Scoreboard background image to cover the ingame one (at the loss of Objective Bounty information)
- Extend the scoreboard and put the Objective Bounty information onto it (don't know if that's possible / easy to implement)
- If the user has the toggles for Team Names, Team Scores and/or Team icons on, but the one for the Scoreboard is toggled off, show the Team Names/Scores/Icons next to the ingame scoreboard (needs an additional check and might not look perfect, but provides all the data)

Attached is a screenshot of the problem
![scoreboard](https://user-images.githubusercontent.com/56082272/154846750-39d66bd9-6cd1-47f6-b425-dda50062f23a.png)

**Comment by floh22** [comment]
To customize, change the scoreboard yourself, all positions, backgrounds, etc are customizable. Try changing the ingame.json file and images in the ingame overlay.

Also its not meant to cover it, you should hide the scoreboard in the beginning of the game. There is a config option to do that automatically for you
