### ISSUE TITLE
[HELP] App never connects to the league client

### ISSUE THREAD

**Issue by Taimoor-Tariq** [floh22/LeagueBroadcastHub#126]
I downloaded the latest release and ran the `LeagueBrodcast.exe`. But the app always says I'm disconnected from the client even after going into a game.
![image](https://user-images.githubusercontent.com/45585081/154949528-3bfba7ef-4471-4d18-95c4-20432e2c6180.png)

**Comment by floh22** [comment]
Please use the issue template
