### ISSUE TITLE
[BUG] New Drakes are not implamented

### ISSUE THREAD

**Issue by poltar96** [floh22/LeagueBroadcastHub#129]
**Describe the bug**
If one of the Teams slain an Hextech Drake (maybe Chemtank aswell, atm disabled) and you activated the Objective Pop Ups (Spawn and/or Kill) it won't appear.
After a short View in the Folders its missing in the Path: Frontend\ingame\images\scoreboardPopUps\Dragon 

btw nice Tool! Keep going!

**Comment by FireFoXz09** [comment]
They will be in the next version.

Temporary solution: https://github.com/floh22/LeagueBroadcast/issues/89
