### ISSUE TITLE
How to change the location according to the length of the team name?

### ISSUE THREAD

**Issue by 21Broo** [floh22/LeagueBroadcastHub#130]
![TeamName](https://user-images.githubusercontent.com/71747410/155308262-d6c71414-4d9e-42e0-a01f-f09c2e4d4729.png)
Is there a solution to solve the problem of not being located in the center when the length of the team name is changed as shown in the picture?

**Comment by daisukedd** [comment]
editing position Ingame.json, X,Y position

**Comment by 21Broo** [comment]
> editing position Ingame.json, X,Y position

I already know how to do that. What I asked is a way to automatically change the location according to the number of letters.

**Comment by 21Broo** [comment]
> > editing position Ingame.json, X,Y position
> 
> I already know how to do that. What I asked is a way to automatically change the location according to the number of letters.

I tried using the "length" function and "if" in Scoreboard Visual.ts, but this is not possible because the team name is set to Blue and Red first and then updated.

**Comment by YI-YEE** [comment]
안녕하세요. 혹시 스코어보드 이미지 파일과 컨피그 좀 받을 수 있을까요..? 

LCK 스타일로 스코어보드 제작 중인데 혹시 도음 주실 수 있을까요 ㅜㅜ

**Comment by floh22** [comment]
ScoreboardVisual line 517 and 531. You would have to write code before those lines respectively to change the offset to your liking.

You could alternatively use different Aligns to achieve similar results, changing align to `center` and change the position in the config
