### ISSUE TITLE
[FEATURE] Add Garena LoL inclusivity / Allow users to choose the LoL folder directly instead of finding Riot Games folder

### ISSUE THREAD

**Issue by yoaprz** [floh22/LeagueBroadcastHub#132]
Without any knowledge whether folder contents in the LoL folder are the same between the Garena and the Riot versions, I think the Garena LoL can be easily included by asking users to directly go to the LoL folder instead of strictly finding the "Riot Games" folder. The supposed Riot Games folder in Garena are named as some random numbers which I think indicate game version. The LoL folder has a different name, which is why I suggested the above change. I think the pictures explain it better. 
![image](https://user-images.githubusercontent.com/61832316/156609325-9382cfc6-16bf-4e46-9453-d41641a99219.png)
![image](https://user-images.githubusercontent.com/61832316/156609355-4caefb13-9d36-4fd9-a692-891ff7e1819d.png)

Also I have trouble finding the appropriate directory format for long directories. Which format am I supposed to use? The first 2 crashes the software even before going into the main UI, while the last one cannot detect the League Client (which I think is the intended result). Still I wish to clarify the correct format.
```
D:\Garena\32771
D:\\Garena\32771
D:\\Garena\\32771
```

**Comment by RabbitJun** [comment]
I have the same problem，I don't know what to write there，everything is wrong.
