### ISSUE TITLE
Program crashing when gold graph or gold tab opened

### ISSUE THREAD

**Issue by EagleCodeRR** [floh22/LeagueBroadcastHub#134]
I realised that the program usually  completely crashes when I try to open the gold graph or the gold tab. This doesn't really happen when the game that I'm spectating has just started. It usually occurs towards the end of a game and opening the program back doesn't really work out for me because it's a live game and when the program is turned back on the kill score or the, dragon's taken by teams is not displayed correctly.

This bug usually happens when spectating a live game and if the gold graph and the gold tab is opened a lot of times the program just crashes without any error. So it probably would be possible to reproduce the bug if you spectate a live game and open the gold graph and the gold tab a lot of times while spectating.

I don't really know what you meant with expected behaviour but I'm gonna assume you meant what did you expect if the bug didn't happen. I was expecting the program not to crash. 

[Crash-2022-01-30-16-17.log](https://github.com/floh22/LeagueBroadcast/files/8207190/Crash-2022-01-30-16-17.log)
[Crash-2022-02-05-21-32.log](https://github.com/floh22/LeagueBroadcast/files/8207191/Crash-2022-02-05-21-32.log)
[Crash-2022-02-06-18-39.log](https://github.com/floh22/LeagueBroadcast/files/8207192/Crash-2022-02-06-18-39.log)
[Crash-2022-01-24-16-29.log](https://github.com/floh22/LeagueBroadcast/files/8207193/Crash-2022-01-24-16-29.log)
[Crash-2022-01-24-19-41.log](https://github.com/floh22/LeagueBroadcast/files/8207194/Crash-2022-01-24-19-41.log)
[Crash-2022-01-25-21-31.log](https://github.com/floh22/LeagueBroadcast/files/8207195/Crash-2022-01-25-21-31.log)
[Crash-2022-01-26-20-16.log](https://github.com/floh22/LeagueBroadcast/files/8207196/Crash-2022-01-26-20-16.log)
[Crash-2022-01-29-00-42.log](https://github.com/floh22/LeagueBroadcast/files/8207189/Crash-2022-01-29-00-42.log)
[Crash-2022-01-26-20-44.log](https://github.com/floh22/LeagueBroadcast/files/8207186/Crash-2022-01-26-20-44.log)
[Crash-2022-01-26-22-15.log](https://github.com/floh22/LeagueBroadcast/files/8207187/Crash-2022-01-26-22-15.log)
[Crash-2022-01-27-15-34.log](https://github.com/floh22/LeagueBroadcast/files/8207188/Crash-2022-01-27-15-34.log)

Windows 10 (10.0.19044) Build 19044

**Comment by FireFoXz09** [comment]
Yeah this bug have been found by many people. All we know for now is that it occurs near the endgame for most of us (for me, it happen around the 35 minutes mark every time) But we arent sure "why". So after the 30 minutes mark, I just stop pressing buttons xD

**Comment by floh22** [comment]
From my limited testing it seems like this is an issue when the amount of gold data is too large to be serialized properly. The website itself does not crash, only the actual program?

**Comment by FireFoXz09** [comment]
Yeah we click on the button for the gold graph (for example) and the program stop responding and close itself (and after that, close the webpage with the graphs so we don't see any overlays at all on OBS)
