### ISSUE TITLE
Background image preload missing for gold graph

### ISSUE THREAD

**Issue by figyl** [floh22/LeagueBroadcastHub#135]
While using 
```
  "GoldGraph": {
    "Position": {
      "X": 965.0,
      "Y": 845.0
    },
    "Size": {
      "X": 740.0,
      "Y": 235.0
    },
    "Background": {
      "UseImage": true,
      "UseVideo": false,
      "UseAlpha": false,
      "FallbackColor": "rgba(19,24,63,255)"
    }
```
in Config/Ingame.json the gold graph background image is not preloaded [here](https://github.com/floh22/LeagueBroadcast/blob/ddf395d22c538d418672c2b8c37943494cd7422a/Overlays/ingame/src/scenes/IngameScene.ts#L50)

**Comment by figyl** [comment]
This results in a weird state where the background is missing while the graph is up. [video](https://www.youtube.com/watch?v=d_5LmDc3KO4)

**Comment by MDvorky** [comment]
I found the fix. Just change from this:
 "Background": {
      "UseImage": true,
      "UseVideo": false,
      "UseAlpha": false,
  to this:
   "Background": {
      "UseImage": false,
      "UseVideo": true,
      "UseAlpha": false,

Don't forgot to save and refresh in the OBS. Just let me know, if it works. :)
