### ISSUE TITLE
[FEATURE] Support ProDraft / Add Overlay for ProDraft

### ISSUE THREAD

**Issue by CryoTheRenegade** [floh22/LeagueBroadcastHub#136]
**Describe the solution you'd like**
Make an overlay that uses the web browser to display ProDraft in a clear and consice way.

**Describe alternatives you've considered**
(I have already made my own overlay for ProDraft tools, but my creativity is very limited.)

**Comment by Coow** [comment]
While I agree that a Overlay for Draftlol or ProDraft would be nice. 
I personally would say that that is outside the scope of this project.
@floh22 Might have another opinion on that

**Comment by floh22** [comment]
If you use ProDraft, then I would recommend not using this projects PickBan feature and relying on ProDraft directly. 

It's quite out of scope to create a new UI for ProDraft, or rather something that should be addressed by another project, at least for now
