### ISSUE TITLE
Unable to find game installation even if everything is correct [BUG]

### ISSUE THREAD

**Issue by ghost** [floh22/LeagueBroadcastHub#139]
**Describe the bug**
Program unable to find league installation on current version

**To Reproduce**
1. Start the tool
2. Probably just have the game / or having it inside a folder, not on root, on a secondary drive

**Expected behavior**

**Material**
Added the route succesfully (Yes, I did save the file to apply changes, also tried with notepad thinking this was the issue)
![image](https://user-images.githubusercontent.com/61168385/162235037-b709efed-598e-4b43-baa4-df6917eebc74.png)

Still get the error
![image](https://user-images.githubusercontent.com/61168385/162235118-8b803b9e-b955-49f5-82d7-8f0b8ea783f3.png)

And to let you see this is indeed the correct route, have tried to download it again, no success whatsoever
![image](https://user-images.githubusercontent.com/61168385/162235201-365aeeb3-1562-4b69-8d84-05104de1bfd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22000.527
 - Lastest .dot net, literally downloded it for this, and did restart

**Additional context**

**Comment by floh22** [comment]
try adding `\\` at the end of each install location. That has been an issue for some in the past

**Comment by TheD4nM4n** [comment]
I am also having this issue. Even after ensuring the JSON contains the Directory with the `Riot Games` folder (which isn't any different from the default path, C:\Riot Games) it isn't working.

**Comment by TheD4nM4n** [comment]
I got it to work by replacing the double backslashes with a single forward slash.
