### ISSUE TITLE
[BUG] BARON & ELDER Timer not working

### ISSUE THREAD

**Issue by challenger087** [floh22/LeagueBroadcastHub#14]
Dear floh22,
First of all, Thank you for giving us the opportunity to use this amazing project, I'd like to ask you if is there any way to get the Baron & Elder Timer working, thank you in advance.

Sincerly

**Comment by floh22** [comment]
Please include logs, screenshots, and descriptions of the issue.
I can't help you find the issue if I don't know what the specific issue is you are having

**Comment by challenger087** [comment]
Issue 1: The baron and Elder timer does blt show you in the screen even if we click the buttons
Issue 2: the dragon icon is not displayed under the scoreboard when a dragon is killed
Please find attaches the log file following the test I made.

Thank you for your help

[Log-2021-05-30-21-59.log](https://github.com/floh22/LeagueBroadcastHub/files/6566919/Log-2021-05-30-21-59.log)
![3](https://user-images.githubusercontent.com/60705849/120120484-e6bb6880-c19d-11eb-9203-1af9b57bf097.PNG)
![2](https://user-images.githubusercontent.com/60705849/120120490-e9b65900-c19d-11eb-8f0b-e9ea7bea1138.png)
![1](https://user-images.githubusercontent.com/60705849/120120492-ec18b300-c19d-11eb-89f7-afb5a6c442ff.png)

**Comment by floh22** [comment]
Do you have League installed in the default location? Logs show that it could not find the install location

Currently the documentation for this is very bad, I apologize. Go into Config/Component.json and find LeagueInstall, which should be something like 
```
"LeagueInstall": [
"C:\\"
]
```
add the folder which contains your "Riot Games" folder to that list, so something like 
```
"LeagueInstall": [
      "C:\\",
      "D:\\Games\"
    ]
```

as for the timers. They only show when a team has the baron or elder buff, otherwise the ingame timers are used. I know the buttons are not very good UI, but they have not been my priority so far

**Comment by challenger087** [comment]
The game is installed in D:\\Games
I did what you told me to do but the drakes icon still not show up on the scoreboard

**Comment by floh22** [comment]
Im guessing the logs still include the line 
```
[21-59-34] [WARNING] Game Location not found. Asking user on startup
```
Try writing `D:\\Games` instead, im not 100% sure how Windows needs it formatted. The next update should tell you on startup if the game install directory was detected.
Also make sure that you the directory you select contains the Riot Games folder. Afaik the league install structure is always
` FOLDER X/Riot Games/League of Legends `, so then you would write the complete path to `FOLDER X` in that line.

If all else fails, create a symbolic link in C:\\ to your folder that contains `Riot Games`. Theres a bunch of tutorials on how to do that on the internet

**Comment by challenger087** [comment]
I downloaded the newest version but i can't run it properly 
[Log-2021-06-01-02-48.log](https://github.com/floh22/LeagueBroadcastHub/files/6572846/Log-2021-06-01-02-48.log)

**Comment by floh22** [comment]
Can you please post the crash log in Logs/Crash Logs?

**Comment by challenger087** [comment]
I installed the game in C:\\ everything now is fine.
I wonder if you have a plan to add the drakes and baron timer in the future ? anyway thank you for help and for your awesome Project :) i hope Riot will certified your App, you really did an amazing job, Good luck!
![image](https://user-images.githubusercontent.com/60705849/120379730-7721b680-c320-11eb-9701-46168516f471.png)
