### ISSUE TITLE
Could not read all champion data from memory. Please submit an issue on github containing the current log and replay

### ISSUE THREAD

**Issue by vitinnbala** [floh22/LeagueBroadcastHub#140]
![unknown](https://user-images.githubusercontent.com/103596373/163236599-bc349f49-826d-4d46-89d0-414ed1c1c281.png)

Toda vez que vou ver um replay ou assistir, isto acontece.
Vi em #127 que tenho que mudar para CR LF, mas eu nao sei fazer isso. Poderiam me ajudar ? 

[Log-2022-04-12-14-45.log](https://github.com/floh22/LeagueBroadcast/files/8483483/Log-2022-04-12-14-45.log)
[Log-2022-04-12-14-51.log](https://github.com/floh22/LeagueBroadcast/files/8483484/Log-2022-04-12-14-51.log)
[Log-2022-04-12-17-09.log](https://github.com/floh22/LeagueBroadcast/files/8483485/Log-2022-04-12-17-09.log)
[Log-2022-04-12-18-03.log](https://github.com/floh22/LeagueBroadcast/files/8483486/Log-2022-04-12-18-03.log)
[Log-2022-04-12-18-33.log](https://github.com/floh22/LeagueBroadcast/files/8483487/Log-2022-04-12-18-33.log)
[Log-2022-04-12-19-01.log](https://github.com/floh22/LeagueBroadcast/files/8483488/Log-2022-04-12-19-01.log)
[Log-2022-04-12-19-19.log](https://github.com/floh22/LeagueBroadcast/files/8483489/Log-2022-04-12-19-19.log)
[Log-2022-04-12-19-29.log](https://github.com/floh22/LeagueBroadcast/files/8483490/Log-2022-04-12-19-29.log)
[Log-2022-04-12-19-54.log](https://github.com/floh22/LeagueBroadcast/files/8483491/Log-2022-04-12-19-54.log)
[Log-2022-04-12-20-11.log](https://github.com/floh22/LeagueBroadcast/files/8483492/Log-2022-04-12-20-11.log)
[Log-2022-04-12-21-01.log](https://github.com/floh22/LeagueBroadcast/files/8483493/Log-2022-04-12-21-01.log)
[Log-2022-04-13-11-20.log](https://github.com/floh22/LeagueBroadcast/files/8483494/Log-2022-04-13-11-20.log)
[Log-2022-04-13-11-23.log](https://github.com/floh22/LeagueBroadcast/files/8483496/Log-2022-04-13-11-23.log)
[Log-2022-04-13-12-51.log](https://github.com/floh22/LeagueBroadcast/files/8483497/Log-2022-04-13-12-51.log)
[Log-2022-04-13-14-00.log](https://github.com/floh22/LeagueBroadcast/files/8483498/Log-2022-04-13-14-00.log)

**Comment by bangingheads** [comment]
Resolved by 74d0f903b3ecde92f3a0b942fafe6add73447c3d.
