### ISSUE TITLE
Missing Offsets

### ISSUE THREAD

**Issue by Buetty227** [floh22/LeagueBroadcastHub#144]
after starting its break down and this is the miss log
[Log-2022-04-29-16-08.log](https://github.com/floh22/LeagueBroadcast/files/8592202/Log-2022-04-29-16-08.log)

**Comment by FireFoXz09** [comment]
Strange. Can you try now that the offsets are updated (Floh updated them friday night). It nerver crashed on my side even when the offsets weren't updated tho.

**Comment by Buetty227** [comment]
oh ye its fine now ty
