### ISSUE TITLE
[BUG] Crash Error

### ISSUE THREAD

**Issue by YI-YEE** [floh22/LeagueBroadcastHub#145]
[Log-2022-05-01-13-02.log](https://github.com/floh22/LeagueBroadcast/files/8598259/Log-2022-05-01-13-02.log)
[Crash-2022-05-01-12-49.log](https://github.com/floh22/LeagueBroadcast/files/8598260/Crash-2022-05-01-12-49.log)
[Crash-2022-05-01-12-54.log](https://github.com/floh22/LeagueBroadcast/files/8598261/Crash-2022-05-01-12-54.log)
[Crash-2022-05-01-13-02.log](https://github.com/floh22/LeagueBroadcast/files/8598262/Crash-2022-05-01-13-02.log)

I was changing the Infopage image, but suddenly it crashed.

**Comment by floh22** [comment]
Looks like you corrupted your ingame.json config. Make a backup and delete your ingame.json. Invalid json will currently crash the program instead of rejecting the invalid file
