### ISSUE TITLE
[FEATURE] Item Purchase Indicators with item name

### ISSUE THREAD

**Issue by OrionCodeDev** [floh22/LeagueBroadcastHub#15]
Hey mate,
Sorry for not using the template, but it doesn't refer to the description of the suggestion. I hope that's not a problem.

I asked the community and one suggestion to improve your tool would be to add a bar with the name of the item you purchased. CBLOL takes advantage of something like this and it really improves the reception and draws attention. I would like to thank you because you are doing a really good job. 

Example from CBLOL:
![newitemswithsubs](https://user-images.githubusercontent.com/47286873/120934149-73fe4000-c6fd-11eb-82f0-2925696354cf.png)

Greetings.

**Comment by floh22** [comment]
Support for item name indicators added in latest release
