### ISSUE TITLE
how can i use this program?

### ISSUE THREAD

**Issue by miki98703** [floh22/LeagueBroadcastHub#150]
after I followed the Installation, I turned on my replay( i turned on the in game function in application ),  

but everything doesn't change without scoreboard disappering!
( and the scoreboard is not changed)

can you give me a some advice?

**Comment by Coow** [comment]
Is the Browser source in OBS above the League Source?
Was the Features enabled in LB itself?

You might also have to "Refresh Cache of Current Page".

**Comment by miki98703** [comment]
Refresh Cache of Current Page? 
how do I do it ? 
I don't know about programing.

**Comment by FireFoXz09** [comment]
This program is made for broadcaster/streamer mostly. Do you stream spectators games and use OBS Studio? It is made to work with that (or any broadcasting software).

This little toturial can help you maybe : https://ritualmotion.com/rmguild/sessions/using-league-broadcast-to-level-up-your-stream/
