### ISSUE TITLE
[BUG]Can't work on Chinese client

### ISSUE THREAD

**Issue by Odin0711** [floh22/LeagueBroadcastHub#156]
I tried many times, but it doesn't work on the Chinese client.
There are many users in China who want to use it, but it doesn't work for Chinese clients

**Comment by floh22** [comment]
As I dont have access to the chinese client and I know the chinese client has extra anticheat protections, i'm not able to develop for it. 

As far as I know, anticheat for the chinese client is quite sophisticated, so I sadly don't think I will ever be able to add support for the region.
