### ISSUE TITLE
Why is there no update?

### ISSUE THREAD

**Issue by sod101316** [floh22/LeagueBroadcastHub#157]
You have confirmed some bugs and requests, but no updates. The most recent update is last year and it's been a long time. please update

**Comment by floh22** [comment]
I work on this in my free time and have work and uni as well.
If you need updates for fixes, you are free to create a PR yourself, I would more than welcome the help.

**Comment by floh22** [comment]
Side note, issues asking "how does this work" or "please fix" will be deleted. I am leaving this up as a showcase and warning of exactly what not to do. 

I am aware many users of this project dont often work with github, but this is not it. It annoys me, spams bug reports, and helps exactly noone.
