### ISSUE TITLE
[BUG] App crashes on startup when fetching v11.12.1 offests

### ISSUE THREAD

**Issue by ignacio-fsstudio** [floh22/LeagueBroadcastHub#16]
The app crashes upon launch, it was working fine until yesterday.

It seems from the crash logs that the app is attempting to fetch offsets for v11.12.1 even though the current version is v11.11. The request is creating a 404 error and the app crashes. I'm attaching the logs for further evidence

[Crash-2021-06-08-19-55.log](https://github.com/floh22/LeagueBroadcastHub/files/6620055/Crash-2021-06-08-19-55.log)
[Log-2021-06-08-19-55.log](https://github.com/floh22/LeagueBroadcastHub/files/6620056/Log-2021-06-08-19-55.log)

Is there a way to force the patch version when launching the app? I couldn't find any

Thanks!

**Comment by floh22** [comment]
It should in theory use the old offsets if it cannot get the new ones, which seemed to be working fine for me when I last tested it.
It seems though that under some certain circumstances it crashes all together without properly performing the checks.

You can also force a version by setting "contentPatch" to the patch in Config/PickBan.json. I know this is a horrible location but I never cleaned up configs during development. Just make sure to change it back to latest when you do not want to force a version anymore

**Comment by ignacio-fsstudio** [comment]
Closing as the update seems to have solved the issue
