### ISSUE TITLE
[BUG] Pick&Ban not showing after new patch + gold not counting

### ISSUE THREAD

**Issue by MDvorky** [floh22/LeagueBroadcastHub#160]
pick&ban phase working and dont working sometimes, even if im restarting the source
and actually, with new patch - gold amount doesnt seem to update as well
only counting kills and turrets and drakes, but not golds

**Comment by FireFoXz09** [comment]
For the Pick&Ban, was it doing this before this patch? (Just curious since I had this problem for months)

For the "gold amount" problem, seems like an offset patch that *floh22* need to do manually. Should be fixed this weekend. :)

**Comment by MDvorky** [comment]
PB was working smoothly, suddenly stop working few days ago. I thought that was due to new patch or something. I tried open and close program. Update the source file but so far nothing works. 

Thank you for the update.

One more question - i already downloaded league broadcast 2.0 - is somehow possible to use this or should go on 1,4,10. version? Thank you for the answer :)

**Comment by AzureAstral** [comment]
Where u found League Broadcast 2.0 ? The latest release is 1.4.10 :o

**Comment by MDvorky** [comment]
I somehow downloaded it :D but there is no exe :D so i cannot run it :D and one more question - is replay possible in 1.4.10? Or?

**Comment by AzureAstral** [comment]
Replay ? What do you mean ?

U have the link for 2.0 ?

**Comment by MDvorky** [comment]
https://github.com/floh22/LeagueBroadcast - this first folder :D

**Comment by MDvorky** [comment]
I just found it :D but there is no exe file :)

Dňa št 9. 6. 2022, 21:40 AzureAstral ***@***.***> napísal(a):
