### ISSUE TITLE
[BUG] Impossible to use 

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#162]
Hello,

When i start the game i have this message : "Could not read all champion data from memory. Please submit an issue on github containing the currend log and replay"

... and the software crash..

I try so many time to restart, game, computer and League Broadcast and impossible to resolve this problem...

[Log-2022-06-09-21-13-0.log](https://github.com/floh22/LeagueBroadcast/files/8873323/Log-2022-06-09-21-13-0.log)
[Log-2022-06-09-21-21.log](https://github.com/floh22/LeagueBroadcast/files/8873324/Log-2022-06-09-21-21.log)
[Log-2022-06-09-20-37.log](https://github.com/floh22/LeagueBroadcast/files/8873325/Log-2022-06-09-20-37.log)
[Log-2022-06-09-20-52.log](https://github.com/floh22/LeagueBroadcast/files/8873326/Log-2022-06-09-20-52.log)
[Log-2022-06-09-20-53.log](https://github.com/floh22/LeagueBroadcast/files/8873327/Log-2022-06-09-20-53.log)
[Log-2022-06-09-20-53-0.log](https://github.com/floh22/LeagueBroadcast/files/8873328/Log-2022-06-09-20-53-0.log)
[Log-2022-06-09-20-54.log](https://github.com/floh22/LeagueBroadcast/files/8873329/Log-2022-06-09-20-54.log)
[Log-2022-06-09-20-56.log](https://github.com/floh22/LeagueBroadcast/files/8873318/Log-2022-06-09-20-56.log)
[Log-2022-06-09-21-11.log](https://github.com/floh22/LeagueBroadcast/files/8873319/Log-2022-06-09-21-11.log)
[Log-2022-06-09-21-12.log](https://github.com/floh22/LeagueBroadcast/files/8873320/Log-2022-06-09-21-12.log)
[Log-2022-06-09-21-13.log](https://github.com/floh22/LeagueBroadcast/files/8873321/Log-2022-06-09-21-13.log)
.

**Comment by meeeww** [comment]
It's for everyone. It broke this patch and we gotta wait for an update
