### ISSUE TITLE
How do you change fonts?

### ISSUE THREAD

**Issue by aeclipsia** [floh22/LeagueBroadcastHub#163]
I know it should be located somewhere in the ingame.json file within config, but I don't know what format it should be typed in. Can someone help me?

Thanks

**Comment by daisukedd** [comment]
in /config/InGame.json in final lines this code:
`
"GoogleFonts": [
    "News Cycle",
    "News Cycle:bold",
    "Droid Sans"
  ],
`
You import Google Fonts or Local fonts installed in system - example:
`
"GoldFont": {
      "Style": "Bold", 
      "Name": "Joyride",
      "Size": "22px",
      "Align": "left",
      "Color": "rgb(230,190,138)"
    },
`
