### ISSUE TITLE
[BUG] Baron Timer and Elder Timer not appear

### ISSUE THREAD

**Issue by syuanlyu** [floh22/LeagueBroadcastHub#166]
When i click the Baron Timer and Elder Timer, nothing happened on the screen when the team kill the Baron and Elder .Is there anything i have to do before i click the Baron Timer and Elder Timer? or how can i fix it?
Another question is the dragon icon not appear under the score after the team kill it.

**Comment by Nezumi2711** [comment]
You can follow this instruction, all bug will be fixed. https://github.com/floh22/LeagueBroadcast/issues/8#issuecomment-839817187

**Comment by syuanlyu** [comment]
Sorry, I am confusing that I should add the following to which file?

[LiveEvents]
Enable=1
Port=34243

**Comment by syuanlyu** [comment]
I add it into Game\Config\game.
But when the match start,it stuck on loading screen.
After a minute, the game crash.

**Comment by syuanlyu** [comment]
That help, thanks.
