### ISSUE TITLE
I want to send my in-game overlay to another computer

### ISSUE THREAD

**Issue by sod101316** [floh22/LeagueBroadcastHub#167]
I want to send my in-game overlay to another computer.
I tried changing localhost to IP, but it was not sent to another computer. what should i do

**Comment by Coow** [comment]
You would need to change the backend URL Parameter aswell I think.
So: http://localhost:9001/frontend?backend=localhost
would become:
http://192.168.5.100:9001/frontend?backend=192.168.5.100

**Comment by sod101316** [comment]
I also changed the backend to ip but it doesn't work

**Comment by daisukedd** [comment]
> You would need to change the backend URL Parameter aswell I think. So: http://localhost:9001/frontend?backend=localhost would become: http://192.168.5.100:9001/frontend?backend=192.168.5.100

Did you get to test this? I'm trying to run LB from another pc to be able to control notifications. Basically having two computers, one just spec and the other controlling the LB.

**Comment by f1llyy** [comment]
> You would need to change the backend URL Parameter aswell I think. So: http://localhost:9001/frontend?backend=localhost would become: http://192.168.5.100:9001/frontend?backend=192.168.5.100

Is this the solution to sending the overlay to a streaming pc? If not, is there a way to do it with the current LB?

**Comment by floh22** [comment]
If the PC is on the same network, you have to find out your local device IP.
If you wish to send the overlay over the internet, you must port forward.

Both techniques are heavily documented on the internet and are a search result away.

Then use the appropriate IP instead of localhost on the device you wish to open the overlay on
