### ISSUE TITLE
Cannot Collect Champion Data

### ISSUE THREAD

**Issue by KharTerra** [floh22/LeagueBroadcastHub#168]
[Log-2022-06-23-16-38.log](https://github.com/floh22/LeagueBroadcast/files/8971184/Log-2022-06-23-16-38.log)

I cannot attach a copy of the replay because I was spectating a friend's game. This issue has, however, happened a number of times today.

**Comment by rapz** [comment]
League client just updated, please wait up to 72hrs till @floh22 update the offsets
