### ISSUE TITLE
Is it possible to change the titles of InfoPage's Gold, XP, CSPM respectively?

### ISSUE THREAD

**Issue by syuanlyu** [floh22/LeagueBroadcastHub#169]
When I open the Ingame.json file, I only see "InfoPage" "Title" "Enabled": true, but I don't know if I can change the text content separately?

**Comment by daisukedd** [comment]
I believe it is possible to edit before compiling LeagueBroadcast, I found these keywords in the repository. But I still don't know how to compile.

**Comment by AzureAstral** [comment]
U can disable the title and you make a background image with the title you want ;)

**Comment by daisukedd** [comment]
@AzureAstral Doing it this way I believe it influences the input and output animation, as they are on the same layer.
