### ISSUE TITLE
abro el programa bien pero en cuanto entro a mi cuenta el programa se cierra y lo vuelvo abrir y se cierra[BUG]

### ISSUE THREAD

**Issue by Slowrik** [floh22/LeagueBroadcastHub#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Material**
* If applicable, add screenshots to help explain your problem.
* Include Logs of when the error occured, as well as the crash log if applicable
* Please include the .rofl replay file if the issue was present while spectating

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 20H1 (May 2020 Update) Build 19041]

**Additional context**

**Comment by Slowrik** [comment]
![prueba](https://user-images.githubusercontent.com/108196749/175789228-4cf8a9ec-a1fd-4e08-8320-3520c981a564.jpg)
de esa manera esta pero el programa se cierra y eso solo pasa cuando ya estoy dentro de la cuenta, si lo abro antes de abrir el cliente jala pero en cuanto entro a la cuenta me sigue pasando lo mismo el programa se cierra

**Comment by daisukedd** [comment]
This automatic closing happens to most people, but to reduce the chances it is important to open the LB after logging into the client and in spectator mode do not advance the timer or go back in time, if you have an album bug in spec mode, wait and advance 1s or 2s

**Comment by Slowrik** [comment]
listo solucionado el problema era del mismo cliente el problema no de la aplicación, solo desinstale y volví a instalar el juego y ya no se me cerro para nada
