### ISSUE TITLE
[FEATURE] How to create offsets?

### ISSUE THREAD

**Issue by baddog86** [floh22/LeagueBroadcastHub#177]
Are there instructions for how to generate offsets each patch, its been a long time since the github was updated with them.

**Comment by floh22** [comment]
I will create a short tutorial in the coming days and add it to the readme, or at least overview of what one would need to do to update offsets. 

This will however require at least some technical knowledge, any dev with some experience should however be able to recreate the steps

**Comment by wsthilaire** [comment]
Thanks, hope you're feeling better :)

**Comment by OrionCodeDev** [comment]
> I will create a short tutorial in the coming days and add it to the readme, or at least overview of what one would need to do to update offsets.
> 
> This will however require at least some technical knowledge, any dev with some experience should however be able to recreate the steps

It's will be huge <3 Waiting for it. Also i have a question CreepScore not be in memory read or it's be hard to get it?

**Comment by OrionCodeDev** [comment]
@floh22 "in the coming days" :D Any updates Sir?
