### ISSUE TITLE
I have 2 pc streaming set up

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#18]
I have 2 pc streaming set up
I been using pick/ban ui no problem 

but I'm stuck on this one

http://localhost:9001/frontend

I though I only need to change localhost to ip address

http://192.111.1.111:9001/frontend

something like that but it doesn't show the overlay

when I put on chrome it does read as League Broadcast Hub

but it doesn't show the overlay

help me please

**Comment by floh22** [comment]
Workaround for now:

1. Download repo and open `Overlays/ingame/variables.ts`
2. Change `backendUrl` to your desired IP
3. In the folder `Overlays/ingame` open cmd and run `npm run build`
4. Copy `Overlays/ingame/dist` to `your LeagueBroadcast Install/Frontend/ingame`
5. Start LeagueBroadcast

I hope this works until I have the time to write a proper fix

**Comment by shinilee** [comment]
thank you I'm not in hurry I'm just getting know this I will test this once I get to home by the way is there anyway that I can use my own overlay? I tried to change img but it only does the mask :(

**Comment by shinilee** [comment]
I tried and I fail on step no.3 so I tried my way after I got an idea from ur help
I went to frontend > ingame and open main.js and search localhost and change to ip address and it work ^^
now I just need to figure it out how to edit the scoreboard for my own image

**Comment by floh22** [comment]
Both multi PC support and Overlay customization added in latest release

**Comment by alexissosa88** [comment]
Hola, pudiste editar el fondo del scoreboard? :3
