### ISSUE TITLE
can someone help me fix this [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#183]
I've already changed fonts I've already increased the font size and it doesn't increase the size when opening the chart.
![image](https://user-images.githubusercontent.com/89580284/185233713-68f718f7-0aab-4ab7-aaa3-eab49111c3ee.png)

here as it is currently in the settings.
![image](https://user-images.githubusercontent.com/89580284/185234215-e2eb632a-cf4b-43ac-854d-07b976d8e1dc.png)

**Comment by overkido** [comment]
can someone help me with this bug, which does not increase the font size in the chart?

**Comment by daisukedd** [comment]
Esse bug rola faz um tempo, na pior das opções só reiniciando ou deixando como está, btw nem sempre precisa usar o gráfico

**Comment by overkido** [comment]
toda partida uso o gráfico por isso preciso saber se tem como arrumar

**Comment by floh22** [comment]
These values have to be changed in source and the frontend rebuilt, there is currently no configuration option for them
