### ISSUE TITLE
The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by Tortron1** [floh22/LeagueBroadcastHub#185]
**Describe the bug**
Game crash when starting to spectate the game

**To Reproduce**
1. Start to spectate a random game
2. Startup the program
3. The program will crash after a few seconds of inactivity 

**Expected behavior**
Program scans the game and transmits to the localhost:9001

**Material**
[Log-2022-08-25-14-11.log](https://github.com/floh22/LeagueBroadcast/files/9424530/Log-2022-08-25-14-11.log)
[Crash-2022-08-25-14-11.log](https://github.com/floh22/LeagueBroadcast/files/9424532/Crash-2022-08-25-14-11.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19042 Build 19042

**Comment by floh22** [comment]
Looks like League API was having difficulties. This in combination with missing offsets causes a crash. Shouldnt happen but is an edge case issue I probably wont fix

**Comment by Tortron1** [comment]
Does this mean that I won't be able to use this program or will it eventually resolve itself?
Because the same problem keeps presenting itself even when switching PC's.
