### ISSUE TITLE
How can I change the scoreboard color?

### ISSUE THREAD

**Issue by meeeww** [floh22/LeagueBroadcastHub#186]
I would like to change the scoreboard color for a custom one. I have searched a lot through the files but I didn't find it yet, so I would please like to know where to find the config to change the RGB or RGBA color. I know this isn't a bug but don't know where to post it. Thanks for your time and sorry for the inconvenience.

**Comment by daisukedd** [comment]
After making the changes it is good to restart the program

**Comment by meeeww** [comment]
> After making the changes it is good to restart the program

That's not what I asked xD

**Comment by meeeww** [comment]
I found it, thanks anyways. In case anyone is interested, it's in the config file inside ..\LeagueBroadcast\Config\Ingame.json and you have to scroll down until line 362 called background.
