### ISSUE TITLE
offsets not working [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#187]
offsets not working, general gold and level don't show

**Comment by daisukedd** [comment]
I contacted the developer and I'm trying to help him

**Comment by OrionCodeDev** [comment]
It's will be easier when we will get promised tutorial for getting offsets. That project be little dead, only updates be about offsets meh.
#177 - one month ago

**Comment by floh22** [comment]
> It's will be easier when we will get promised tutorial for getting offsets. That project be little dead, only updates be about offsets meh. #177 - one month ago

I do this in my free time for free for the community. If you need updates or offsets quicker, feel free to provide those yourself.


Offsets updated and Tutorial posted
