### ISSUE TITLE
[BUG] Color issue 

### ISSUE THREAD

**Issue by dajajaultra** [floh22/LeagueBroadcastHub#189]
Hi! I think there is a bug in Chaos Color for Gold/XP/CSPM, I set up the color green but won't show up

![image](https://user-images.githubusercontent.com/114696213/193124908-f493d557-6027-4122-9f92-ef40dab942c2.png)

![image](https://user-images.githubusercontent.com/114696213/193124494-3fa725b4-c716-4917-98c7-b0cc06d09a58.png)

**Comment by floh22** [comment]
Please use bug reporting template.
Also, looks like a case of delete ingame.json
