### ISSUE TITLE
[FEATURE] Ability to change the background of EXP / Gold Tab, Scoreboard etc

### ISSUE THREAD

**Issue by Ukan0** [floh22/LeagueBroadcastHub#19]
Is your feature request related to a problem? Please describe. 
No. Its not

Describe the solution you'd like A clear and concise description of what you want to happen. 
I want to be able to replace the background files of exp / gold tab etc. I know that i can replace the background of the gold graph by replacing the "CenterCover" at overlay\Frontend\ingame\backgrounds

Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered. Maybe a background color picker in the Ingame tab?

Additional context Add any other context or screenshots about the feature request here.

**Comment by floh22** [comment]
Currently you can change the background color by editing the Ingame.json config. I will be changing this in the future to also support images as well

**Comment by shinilee** [comment]
> Currently you can change the background color by editing the Ingame.json config. I will be changing this in the future to also support images as well

that doesn't change scoreboard. Scoreboard change back to original blue color.

![image](https://user-images.githubusercontent.com/82671596/122644508-8efc8700-d0e3-11eb-93e1-8043e3babbb4.png)
