### ISSUE TITLE
Patch 12.19 offset

### ISSUE THREAD

**Issue by discodanz** [floh22/LeagueBroadcastHub#191]
Hi team,

12.19 has just landed. Wondering what the ETA will be for updated offsets?

-Dan

**Comment by discodanz** [comment]
[Log-2022-10-05-09-15.zip](https://github.com/floh22/LeagueBroadcast/files/9710451/Log-2022-10-05-09-15.zip)

Attached log.

**Comment by discodanz** [comment]
If anyone has the capability to update the offsets please reach out. Happy to pay. We have an LAN in 24hrs that we have spent a lot of time building a Hud for. Thank you :D

**Comment by benholness** [comment]
@discodanz is there anyway we can be taught how to do these offsets ourselves?

**Comment by discodanz** [comment]
Hey Ben,

Yup! The readme and can found here: https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight

**Comment by benholness** [comment]
Thanks @discodanz! Appreciate the ninja response
