### ISSUE TITLE
[FEATURE] Stream Deck Compatibility

### ISSUE THREAD

**Issue by MDvorky** [floh22/LeagueBroadcastHub#192]
I was wondering,

would it be possible to somehow make it work with the Stream Deck? Do app for Stream Deck store that is available and be able to control the LB via Stream Deck. I was just wondering.

**Comment by GhostSenseiFR** [comment]
It would be one of the most useful feature for LB. Having to alt tab the game is unconveniant and it can mess up your ingame camera.

If anyone knows how to do this, It would be amazing.

**Comment by floh22** [comment]
At some point I may create a web interface, which would solve this issue. But no native support for third platforms is planned
