### ISSUE TITLE
Champ slect doesnt appear [BUG]

### ISSUE THREAD

**Issue by ElPorito** [floh22/LeagueBroadcastHub#193]
**Champ slect doesnt appear**
I follow the instruccions, the broadcast stays conected to lol client, but when I start the champ select the broadcast doesnt show something in the browser and obs... I clean cache but doesnt work

![image](https://user-images.githubusercontent.com/87684258/194680352-55c0da0c-b3df-4dfa-ad7e-e81cd3aacdec.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Version [1.4.106 (Nov 2021 Update) ] 
 - Local Client Version 12.19.1

**Additional context**

[Log-2022-10-07-20-02.log](https://github.com/floh22/LeagueBroadcast/files/9738094/Log-2022-10-07-20-02.log)

**Comment by floh22** [comment]
Might have been win 11 issue, try again with the latest update
