### ISSUE TITLE
When I open Leaguebroadcast,it will get stuck at "Retrieving latest patch info" and crash.

### ISSUE THREAD

**Issue by syuanlyu** [floh22/LeagueBroadcastHub#198]
When I open Leaguebroadcast,it will get stuck at "Retrieving latest patch info" and crash.
I have redownloaded but it keeps happening.
![image](https://user-images.githubusercontent.com/107873438/199639700-c65685f5-12b9-4d84-af65-f77a23466700.png)

**Comment by TheD4nM4n** [comment]
Could you send the crash log, available in the Crashes folder within the directory you have LeagueBroadcast?

**Comment by syuanlyu** [comment]
[Crash-2022-11-03-16-31.log](https://github.com/floh22/LeagueBroadcast/files/9926935/Crash-2022-11-03-16-31.log)

**Comment by thangoghd** [comment]
[Crash-2022-11-03-18-27.log](https://github.com/floh22/LeagueBroadcast/files/9927875/Crash-2022-11-03-18-27.log)

**Comment by floh22** [comment]
This means either your config files are broken or you cannot reach Community Dragon servers. Try deleting `Config\Component.json`. If that does not work, it must be something with the internet connection

**Comment by thangoghd** [comment]
still not working but tks for your help.

**Comment by floh22** [comment]
Can you tell me what you see when you open https://raw.communitydragon.org/latest/content-metadata.json on the same PC?

**Comment by thangoghd** [comment]
{
    "version": "12.21.4770420+branch.releases-12-21.content.release"
}

**Comment by syuanlyu** [comment]
{
    "version": "12.21.4770420+branch.releases-12-21.content.release"
}

**Comment by syuanlyu** [comment]
{
    "version": "12.21.4770420+branch.releases-12-21.content.release"
}

**Comment by curlydoggy** [comment]
same issue in 1.5.25.0 version...
This is my crash log.
[Crash-2022-11-09-00-25.log](https://github.com/floh22/LeagueBroadcast/files/9962661/Crash-2022-11-09-00-25.log)

**Comment by syuanlyu** [comment]
I can open version 1.4.106 today,but i can not open version 1.5.24.0 .

**Comment by floh22** [comment]
Are these issues resolved? As far as I can tell I think I found the issue, but it would be good if you could confirm that for me
@curlydoggy @syuanlyu @thangoghd

**Comment by syuanlyu** [comment]
Yes,my issues resolved.
