### ISSUE TITLE
Custom Scoreboard

### ISSUE THREAD

**Issue by PavlitooPL** [floh22/LeagueBroadcastHub#20]
Hello,

I have a question. Can you please tell us how we can change the scoreboard to as attached? How can we change the background into a picture, or the colors as in the picture, and is it also possible with dragons?
![202576289_395798925069552_3994073255724810970_n](https://user-images.githubusercontent.com/86074972/122449950-bd287c80-cfa6-11eb-81a1-cea70c0a0ae2.png)

**Comment by floh22** [comment]
This currently is not a feature.

If you wish for me to implement it for you, contact me personally and we can see what I can do

**Comment by shinilee** [comment]
> This currently is not a feature.
> 
> If you wish for me to implement it for you, contact me personally and we can see what I can do

I'm interested how can I contact you on personal?

**Comment by floh22** [comment]
you can contact me via twitter [@larseble](https://twitter.com/larseble)

**Comment by shinilee** [comment]
it said I can't send message to you on twitter

**Comment by shinilee** [comment]
> you can contact me via twitter [@larseble](https://twitter.com/larseble)

I sent message but you never respond me from twitter

**Comment by floh22** [comment]
sorry, im rather busy at the moment. Im reworking the frontend anyway, so I will look to add this feature
