### ISSUE TITLE
Update Freezing at Downloaded 1851/1852 Assets

### ISSUE THREAD

**Issue by Sigmna090** [floh22/LeagueBroadcastHub#200]
Froze at 1851/1852 when trying to update. Decided to uninstall all and just install it all again but the same issue still happened when trying to open for the first time. 
![image](https://user-images.githubusercontent.com/117332147/199645255-da0f1185-2c4c-471f-a23c-790a0d9f1e29.png)

**Comment by floh22** [comment]
Please use the Bug report template.
Include logs and crash logs where possible
