### ISSUE TITLE
[BUG] In-game overlays not loading

### ISSUE THREAD

**Issue by benholness** [floh22/LeagueBroadcastHub#201]
Just updated to the latest update provided for this software and when I load into a game replay, the overlays are not showing up when they were before (http://localhost:9001/frontend?backend=localhost)

Just also tried it out in a custom game where I was spectating and the overlays are not showing up for that browser source either.

I've also tried using a fresh download of the program and the same issue persists.

Here is the log for reference (it looks like the line `[08-39-21] [WARNING] Could not update State: System.Private.CoreLib -> One or more errors occurred. (A task was canceled.)` might have something to do with it?)
[Log-2022-11-03-08-28.log](https://github.com/floh22/LeagueBroadcast/files/9926743/Log-2022-11-03-08-28.log)

![In-Game Overlay Missing](https://user-images.githubusercontent.com/28854222/199677886-19c988c4-1225-4a68-bf07-74bcc5955aff.PNG)

**Comment by Nanovic30** [comment]
Same issue there

**Comment by MDvorky** [comment]
Not working here either

**Comment by floh22** [comment]
alright. I don't have much time today but I'll try to look at it later, seems my testing is insufficient

**Comment by floh22** [comment]
would you be able to send me the replay as well as the timestamp of when the crash occurs?
From the log it would seem it worked fine for 2 minutes.
It would also be helpful if you could show browser logs incase any errors pop up there

**Comment by Nanovic30** [comment]
Im not able to test it again right now but for my part it never loaded any overlay, even if the game was detected (all players were shown into LeagueBroadcast but nothing happened with the browser source)
I tried it with different replays and the result was the same

**Comment by benholness** [comment]
Hey @floh22, unfortunately Github doesn't support uploading the replay file type but I did find something interesting when I looked at the browser console logs as requested. 

Looking at the browser console logs, I found the in-game overlays had some kind of websocket connection error but the pick and ban overlays had no problem at all (see attached logs and screenshots for reference). 

We have a tournament tomorrow and I was hoping we could use these overlays for then as they were all working until the LOL patch updated 2 days ago.

Appreciate you're trying to find a solution for this.

Program Log: [Log-2022-11-04-09-15.log](https://github.com/floh22/LeagueBroadcast/files/9936774/Log-2022-11-04-09-15.log)

![In-Game Console Log](https://user-images.githubusercontent.com/28854222/199938509-9d49526e-7813-4ec1-acb0-658a9fad08d9.PNG)
In-Game Browser Console Log: [in-game-browser-console.log](https://github.com/floh22/LeagueBroadcast/files/9936779/in-game-browser-console.log)

![Pick and Ban Console Log](https://user-images.githubusercontent.com/28854222/199938540-8f441bce-f64f-4fde-861a-3f8fc7b86101.PNG)
Pick and Ban Browser Console Log: [pick-and-ban-browser-console.log](https://github.com/floh22/LeagueBroadcast/files/9936781/pick-and-ban-browser-console.log)

**Comment by floh22** [comment]
I cant seem to replicate the issue. Can you contact me on Twitter or Discord so we can try resolving this together?
Nothing about the frontend changed, so troubleshooting looks to be a bit tricky

**Comment by benholness** [comment]
@floh22 sure thing happy to do that, join my Discord and we can organise troubleshooting this together

https://discord.gg/pjuV2Yu8

**Comment by benholness** [comment]
@floh22 no worries, what is your Discord tag?

**Comment by issaclarke** [comment]
> Hey @floh22, unfortunately Github doesn't support uploading the replay file type but I did find something interesting when I looked at the browser console logs as requested.
> 
> Looking at the browser console logs, I found the in-game overlays had some kind of websocket connection error but the pick and ban overlays had no problem at all (see attached logs and screenshots for reference).
> 
> We have a tournament tomorrow and I was hoping we could use these overlays for then as they were all working until the LOL patch updated 2 days ago.
> 
> Appreciate you're trying to find a solution for this.
> 
> Program Log: [Log-2022-11-04-09-15.log](https://github.com/floh22/LeagueBroadcast/files/9936774/Log-2022-11-04-09-15.log)
> 
> ![In-Game Console Log](https://user-images.githubusercontent.com/28854222/199938509-9d49526e-7813-4ec1-acb0-658a9fad08d9.PNG) In-Game Browser Console Log: [in-game-browser-console.log](https://github.com/floh22/LeagueBroadcast/files/9936779/in-game-browser-console.log)
> 
> ![Pick and Ban Console Log](https://user-images.githubusercontent.com/28854222/199938540-8f441bce-f64f-4fde-861a-3f8fc7b86101.PNG) Pick and Ban Browser Console Log: [pick-and-ban-browser-console.log](https://github.com/floh22/LeagueBroadcast/files/9936781/pick-and-ban-browser-console.log)

I am having exactly the same issue. Nothing shows up nor In-Game browser or in the Pick and Ban Browser.

**Comment by floh22** [comment]
Fixed in 1.5.25
