### ISSUE TITLE
[BUG] Overlay closes when the LIVE game end (even if I'm still spectating)

### ISSUE THREAD

**Issue by FireFoXz09** [floh22/LeagueBroadcastHub#204]
**Describe the bug**
The overlays shutdown when there 3 min approx left to the game (the spectator delay). The client now tell us when the game ended by showing the endgame scoreboard (when I checked my League Client), so I guess League Broadcast stop working for that? (Or I am unlucky?)

No crash logs because LeagueBroadcast think it ended normally.

I've reproduced this 2 games in a row on stream if needed. I'm using the latest build (1.5.25), updated via the automatic update from 1.4.106

[Log-2022-11-07-19-46.log](https://github.com/floh22/LeagueBroadcast/files/9957025/Log-2022-11-07-19-46.log)

**Comment by FireFoXz09** [comment]
Tested again, this seems to happen in custom games only (spectating a friend in any premade game mode doesn't do this.) The League Client show the result when the players have ended the custom games, removing the "Game is still in progress..." screen, telling LeagueBroadcast that the game technically ended.

The problem happens with tournament code and without a tournament code, as long this is a Custom Game. (Summoner's rift and Howling Abyss have both been tested and it does that on both)

**Comment by floh22** [comment]
Fixed in 1.5.37
