### ISSUE TITLE
[BUG] LB imediately closes after I started it

### ISSUE THREAD

**Issue by NicoSchulz00** [floh22/LeagueBroadcastHub#205]
Since this week I can't start League Broadcast anymore. Everytime I am trying to start the software, I see the "startscreen" for about 2 seconds before it closes down.

I have the newest version of League Broadcast (1.5.25) and the .Net Framework 6.0.11. Both are installed at my C: drive, the riot games folder is meanwhile on my D: drive, but I allready adjusted the path for League Install in the config file.

Desktop:
 - OS: Windows 10
 - Version 21H2

I added both, the newest log and the crash log. Would be very thankful for any help!

[Log-2022-11-11-11-48.log](https://github.com/floh22/LeagueBroadcast/files/9989648/Log-2022-11-11-11-48.log)

[Crash-2022-11-11-11-48.log](https://github.com/floh22/LeagueBroadcast/files/9989650/Crash-2022-11-11-11-48.log)

**Comment by floh22** [comment]
fixed in 1.5.37
