### ISSUE TITLE
[BUG] Unable to download data, "please download farsight" error

### ISSUE THREAD

**Issue by OnarrCaster** [floh22/LeagueBroadcastHub#208]
I've been using version 1.5.37 without fail for the last week but all of a sudden it started prompting an erro saying data could not be downloaded (as if there was an update) and it asks me to either write or download the farsight.json file. 

I still get the same issue when trying to delete the current installation and re-installing. I do not know much about code or github, so if there'a a way to download that farsight file separately, I have not found it.

1. Go to your installation path
2. Open LeagueBroadcast.exe
3. Update sequence animation goes through

I am using this for a lol league we're doing in our country (the only one) with Riot's license and we would like to maintain the high quality we achieved through LB

![image](https://user-images.githubusercontent.com/120121703/206504477-2f17c661-a109-4ced-b289-6275c8277c1d.png)

**Desktop (please complete the following information):**
 - Windows 11 Pro
 - Version [22H2] 22621.900 Windows Feature Experience Pack 1000.22638.1000.0

**Comment by floh22** [comment]
Could you post error logs as well? This usually happens only after a patch and offsets havent been updated yet

**Comment by OnarrCaster** [comment]
Issue resolved itself by deleting farsight and forcing a re-download. Thanks Floh!
