### ISSUE TITLE
[BUG] team gold bug

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#209]
bug in the gold of the teams, in a match it's right can someone help fix it?
![drag e inib](https://user-images.githubusercontent.com/89580284/206874948-0f9e8213-3660-43d5-9c74-86b7be1c4f0e.png)

**Comment by MariusSurGithub** [comment]
I have the same bug, please help us 🥲

**Comment by OnarrCaster** [comment]
Issue seems to be present for everyone, most likely something that happened post patch @floh22 please help us!

@overkido btw how'd you set-up the baron power play feature?, did you code it yourself?

**Comment by Coow** [comment]
Yea, this is probably something that happend due to Patch 12.23b. Maybe it changed some memory mappings

**Comment by overkido** [comment]
> @overkido btw how'd you set-up the baron power play feature?, did you code it yourself?

"@OnarrCaster  yes myself who configure the baron updates and all the rest too."

**Comment by overkido** [comment]
It's for the new championship here that I'm developing the visual identity, almost everything is ready for the api, just a few adjustments are missing, I would also like to be able to adjust the font size in the different gold of the teams in the graph, but it's something impossible because I've tried everything and it doesn't change. 
@OnarrCaster

**Comment by floh22** [comment]
Looks like memory changed slightly in 12.23b or I messed up when updating. Either way, deleting farsight.json should trigger a redownload and fix the issue.

Edit: I just messed up while updating to 12.23

**Comment by overkido** [comment]
could you add a custom timer/logo for the drags and herald/baron, to help us due to the bug in the esports timer of the client itself that does not show the new dragons, if it is not asking too much already asking, like worlds??? @floh22
