### ISSUE TITLE
can't open anymore

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#21]
today I just test it and it just fade away it used to work tho... I want to test the post game if it work

**Comment by floh22** [comment]
This tells me nothing. The issue template is there to help you so I can tell what the issue even is.

 Please provide logs and crash logs as well as screenshots if applicable

**Comment by shinilee** [comment]
I test on my work pc and it open but it crash
and dragon icon not showing :(
[Log-2021-06-24-09-52.log](https://github.com/floh22/LeagueBroadcastHub/files/6709774/Log-2021-06-24-09-52.log)
[Crash-2021-06-24-09-55.log](https://github.com/floh22/LeagueBroadcastHub/files/6709776/Crash-2021-06-24-09-55.log)

**Comment by floh22** [comment]
Hotfix 6af968c fixes this issue
