### ISSUE TITLE
[BUG] Patch 13.1.1 - Farsight.json error - Can't load in-game overlays

### ISSUE THREAD

**Issue by benholness** [floh22/LeagueBroadcastHub#211]
Hey @floh22,

Got an issue with the program. I open it up, load into a game and this message pops up.

![Capture](https://user-images.githubusercontent.com/28854222/212471517-5b738d63-fc21-4a95-b2a0-f9a320979c77.PNG)

Is it something to do with Farsight.json file not being up-to-date with the new patch?

I've also tried a new installation of the program and getting the same result.

Here is the log file for reference too: 
[Log-2023-01-14-12-27.log](https://github.com/floh22/LeagueBroadcast/files/10417311/Log-2023-01-14-12-27.log)

**Comment by FireFoXz09** [comment]
As the error says, offsets haven't been updated by Lars / floh22 since the new season (patch 13.1). You can either wait for him to update it or do it yourself by learning how to fetch them. Here a little tutorial how to do this written by Lars/floh22

> as a bit of a guide until I can make something better
> 1. https://www.unknowncheats.me/forum/league-of-legends/320116-dump-lol-addresses-guide.html
> 
> you need the how to dump part of this. This is for the OffsetManager value as well as the LocalPlayer value. You dont NEED the LocalPlayer, but it makes step 2 far easier. You can ignore everything after step 3 which deals with IDA
> 
> 2. https://www.unknowncheats.me/forum/league-of-legends/423786-reclass.html
> 
> This is the bread and butter of how to get the values. What you do is open up a practice tool game, and then u use the localplayer value, and then that is your player. Use old values as rough guides where the values should be. Buy items, take damage, etc, so see if anything updates
> https://www.unknowncheats.me/forum/2590879-post1736.html
> This is how to have League not crash when you use ReClass

**Comment by benholness** [comment]
Thanks @FireFoXz09, I'll try to do this myself however a video tutorial format of this would be so much better.

If someone would be able to do that, I'd be more than happy to contribute easier.

**Comment by FireFoXz09** [comment]
Seems like we got an update for patch 13.1.1 in the offsets folder. Can you try launching LeagueBroadcast again and see if it works now?

**Comment by benholness** [comment]
Appear to be working now @FireFoXz09, thanks for letting me know.

But a video tutorial showing us how to update this ourselves would be awesome, ngl :)

**Comment by dcapape** [comment]
Are 13.1.1 offsets still working? The game is on 13.1.4.. but Dragontail is on 13.1.1 is it supposed to be working like this? My Farsight instance cannot find Champions.
