### ISSUE TITLE
make a video lesson on offsets so we can make update [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#215]
make a video lesson on offsets so we can make update,

**Comment by FireFoXz09** [comment]
https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight

Maybe this could help, this is a bit more detailled on how to do this (still need basic programaming knowledge)

**Comment by floh22** [comment]
The text tutorial contains all anyone needs to update the offsets. Most of the work is in the setup, actually updating offsets is far less work. I may at some point make a video tutorial, but I honestly doubt it. If anyone who is able to update the offsets wishes to make a tutorial, I would add it to the repository for others to use
