### ISSUE TITLE
Someone who works at the root of the api to add new functions to it, such as a drags? [FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#217]
Someone who works at the root of the api to add new functions to it, such as a drags timer and other things that I need for my championship, we are looking for someone who really knows how to add a service that will be paid, contact me urgently.

would it be possible for you to be able to do this, put some new functions in the api and we would pay for the new functions? @floh22 

[https://linktr.ee/iagomouraof](url)

**Comment by overkido** [comment]
@floh22

**Comment by floh22** [comment]
I doubt anyone currently other than me has much experience with this program, and I dont think that will change. The program is a architectural mess and changing stuff is a nightmare.

If you wish to get custom paid for tools, as far as I know the people over at RC Volunteers and their League Production toolkit do custom work, you may have more success asking them
