### ISSUE TITLE
[BUG] Timers (Elder Baron) frozen since from start.

### ISSUE THREAD

**Issue by empvini** [floh22/LeagueBroadcastHub#22]
**Describe the bug**
The timers of Elder and Baron are appearing since the start and stay there even with options not selected

**To Reproduce**
nothing special, just oppened

**Expected behavior**
The timers appearing only when I select it on app.

**Comment by floh22** [comment]
Can you please provide logs when this behavior occurs?

**Comment by empvini** [comment]
Sorry, i got what happens - Streamlabs OBS Browser isnt compatible with API

**Comment by floh22** [comment]
Any browser should work fine with the program. You may have to check an option like "refresh source when active" or similar.

If an option like that does not fix it, can you open the frontend in a browser and check the browser console for any errors?

**Comment by floh22** [comment]
closed due to inactivity
