### ISSUE TITLE
is there any Simple Way to Change stuff from the Ingame Config Folder?

### ISSUE THREAD

**Issue by SignoreNinja** [floh22/LeagueBroadcastHub#222]
Hello firstly i like this project and Rly like to use this program while i Broadcast.

Now i wanted to re-design The Ingame overlay and added new Dragon pictures and that stuff, but i have now the problem that i wanted to change the Scoreboard, but the Program won't use the new PNG data. Which is also the only picture with that name in the folder and I replaced it. So I also looked at the JSON Code and I found the Background Picture is false and even when I change it to true it won't work. And if I restart the program, the JSON File also resets that background settings. 
pls send help.

**Comment by FireFoXz09** [comment]
Make sure that you close and restart the program to be sure it updates. Also, refresh your source in OBS to be sure it updates with the new image.

**Comment by SignoreNinja** [comment]
i already tried that but it wont work for stuff like the scoreboard

**Comment by FireFoXz09** [comment]
Are you running as an administrator no the PC? or the software? I never had this problem where the json files i modify get reset... Itusually saves any changes I do when I close Notepad and reopen the file...

Can you send a screenshot of the lines you,re editing? Just to be sure you,re at the right place. I'll try to test this on my side too this weekend but I had no problem editing my scoreboard a few days ago.

**Comment by SignoreNinja** [comment]
Oh i didnt Open it as Admin but i will try it and update you guys
i tried to changed UseImage to true and UseAlpha to False and now it looks lie this in the Ingame.json File

![image](https://user-images.githubusercontent.com/80975446/219776893-9a409129-f4e4-47aa-ab1f-d447d7a49db5.png)

**Comment by floh22** [comment]
If you want to use a PNG, which is an image, set UseImage to true and UseAlpha to false if you have the alpha in the PNG already, or keep it on true. This stuff should auto update without closing the website or program
