### ISSUE TITLE
Could not read all champion data from memory. Please submit an issue on github containing the current log and replay.[BUG]

### ISSUE THREAD

**Issue by pumdi** [floh22/LeagueBroadcastHub#224]
I have this issue...
"Could not read all champion data from memory. Please submit an issue on github containing the current log and replay"

how to fix this issue...? help!

my language = kr_KR

[Log-2023-02-20-02-05.log](https://github.com/floh22/LeagueBroadcast/files/10777444/Log-2023-02-20-02-05.log)

**Comment by floh22** [comment]
possibly was an offset issue, check again this patch and see if this behavior is fixed
