### ISSUE TITLE
[BUG] Dragon Timer 

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#226]
all dragon timer shows to cloud timer

![image](https://user-images.githubusercontent.com/82671596/221249850-825e6bb5-e769-49c4-8ec7-837c3f578de1.png)

first dragon was cloud and mountain and ocean but the dragon timer stuck at cloud dragon image

elder dragon image off but this one can be easy fix from me but just letting you know

![image](https://user-images.githubusercontent.com/82671596/221252023-f3d2cc29-68c8-45cd-8c9f-decd6f1f6680.png)

first, second dragon respawn doesn't work only working start from 3rd dragon

**Comment by floh22** [comment]
Can you open the browser console during the game and post the results? You can also skip around in the game and it should update accordingly, or at least show the messages in the console.

**Comment by FireFoXz09** [comment]
Also, could be nice to have the option to activate or not this feature, with a true or false option (example: "Enabled: true," or Enabled: false,") like for the scoreboard items. Only option for now is to move it out of the screen with the X and Y position.

As I love this addition, this can be a good option to have for thoses who don't want to use it or prefer the classic in-game timer overlay.

**Comment by floh22** [comment]
Fixed in latest release
