### ISSUE TITLE
API closing after updating to patch 13.4 [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#227]
API closing after updating to patch 13.4

[Crash-2023-02-24-23-17.log](https://github.com/floh22/LeagueBroadcast/files/10830078/Crash-2023-02-24-23-17.log)

**Comment by floh22** [comment]
Is this on a fresh install? If not, try deleting both Component.json and Farsight.json. The latest update breaks some config files, so that may be the issue.

Otherwise, can you post these two files?

**Comment by overkido** [comment]
Install 0 and I was added my changes again and everything ok, I saw after some changes came in, I thank you.

Taking advantage of thanks for adding dragon time, as soon as possible add the herald time and right after Baron or even only Baron JPA would help a lot with the change to the championship here from Tier 2 thanks

**Comment by overkido** [comment]
a doubt, how do I put the numerical score that I saw in the code that has the option but I don't know how to put it, it removes this other doubt too.

![image](https://user-images.githubusercontent.com/89580284/221364650-594e7e17-82e4-4a83-b9da-fe37261bb7cf.png)

**Comment by floh22** [comment]
you would have to change the overlay code for that. At some point I will rewrite it to add support for stuff like that, but for now you would have to manually change it

> Install 0 and I was added my changes again and everything ok, I saw after some changes came in, I thank you.
> 
> Taking advantage of thanks for adding dragon time, as soon as possible add the herald time and right after Baron or even only Baron JPA would help a lot with the change to the championship here from Tier 2 thanks

Baron/Herald timers should be added somewhere within March, though I cannot promise anything.

**Comment by overkido** [comment]
> 

what is your twitter or any social network to follow, I wanted to know is it possible to do this type of project also for this broudcast project or by a separate api.

![image](https://user-images.githubusercontent.com/89580284/221385202-10dc3202-ba2f-4462-a45a-e5df72e9d8ea.png)

**Comment by Coow** [comment]
> > 
> 
> what is your twitter or any social network to follow, I wanted to know is it possible to do this type of project also for this broudcast project or by a separate api.
> 
> ![image](https://user-images.githubusercontent.com/89580284/221385202-10dc3202-ba2f-4462-a45a-e5df72e9d8ea.png)

For End of Game you can check out RCVolus League-Prod-Kit: https://github.com/RCVolus/league-prod-toolkit
It requires a bit of setup and a learning curve. But it has a similar End of Game screen like you see on your screenshot.
It works great in addition to League Broadcast from personal experience!

**Comment by floh22** [comment]
Timers added. Rest probably at some point in future, but no timeline or promise. Closing for now
