### ISSUE TITLE
[BUG] Program crashed

### ISSUE THREAD

**Issue by challenger087** [floh22/LeagueBroadcastHub#23]
hey! how you doing ? i got a new error, when the drake in taken the program close immediately
here the crash log :
[Crash-2021-06-24-15-07.log](https://github.com/floh22/LeagueBroadcastHub/files/6709877/Crash-2021-06-24-15-07.log)

[Log-2021-06-24-14-52.log](https://github.com/floh22/LeagueBroadcastHub/files/6709888/Log-2021-06-24-14-52.log)

**Comment by floh22** [comment]
can you send the replay of the game where this occurs? I cannot seem to recreate this issue

**Comment by floh22** [comment]
Hotfix 6af968c should prevent this issue
