### ISSUE TITLE
can someone help me? [FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#234]
can someone help me, does anyone know how to remove the team and put the time running on top in the team color as in the msi, and put the bans on top?

and put the team's acronym in the middle as it is in the image?

![image](https://user-images.githubusercontent.com/89580284/223744949-3b5f8923-5bc4-4293-bd38-4f5708d05310.png)
![image](https://user-images.githubusercontent.com/89580284/223745291-ea836b89-dd96-45fb-9402-3f5653585353.png)

**Comment by floh22** [comment]
You would have to edit the pickban frontend website yourself and then rebuild it, changing this is in the program or by configs is not supported. A tutorial on how to develop and build the frontends is in the frontends folder of this repo
