### ISSUE TITLE
After 13.6.1 update program is not working correctly [BUG]

### ISSUE THREAD

**Issue by EagleLOL** [floh22/LeagueBroadcastHub#239]
![Ekran görüntüsü 2023-03-23 214208](https://user-images.githubusercontent.com/127695194/227316821-a75f6d32-2916-4a8f-860f-91677ae11c87.jpg)
![Ekran görüntüsü 2023-03-23 214314](https://user-images.githubusercontent.com/127695194/227316837-5181c7f3-73b2-4cf5-adf7-af70138e74db.jpg)

As you can see the dragon timer is showing the wrong dragon and the tabs are not working at the moment. The program sometimes crashes too but I couldn't find a crash log for that.

**Comment by EagleLOL** [comment]
UPDATE 

![image](https://user-images.githubusercontent.com/127695194/227319675-bc214313-b845-4372-871c-969704ea521d.png)
fixed it by copying and pasting this to my : farsight text file thats in config folder

**Comment by UnifiedHyper** [comment]
Did you do anything else for this? Cause I updated the offsets as you specified and it still didn't work

**Comment by EagleLOL** [comment]
this is the only thing I changed

**Comment by UnifiedHyper** [comment]
Damn. Even when I tried a fresh install that did not work.

**Comment by EagleLOL** [comment]
Hey just noticed that it's broken again. There was an update today that riot did. I think it was a hotfix for the new champion and it looks like it broke the program again.

**Comment by EagleLOL** [comment]
UPDATE (FIXED AGAIN)

{
"OffsetVersion": "13.6.1",
"GameOffsets": {
"Manager": "0x186e154",
"MapCount": "0x2c",
"MapRoot": "0x28",
"MapNodeNetId": "0x10",
"MapNodeObject": "0x14"
},
"ObjectOffsets": {
"ID": "0x8",
"NetworkID": "0xb4",
"Team": "0x34",
"DisplayName": "0x54",
"DisplayNameLength": "0x64",
"Pos": "0x1dc",
"Mana": "0x29c",
"MaxMana": "0x2ac",
"Health": "0xe7c",
"MaxHealth": "0xe8c",
"CurrentGold": "0x1bb4",
"GoldTotal": "0x1bc4",
"EXP": "0x32ec",
"Name": "0x2b04"
},
"FileVersion": "1.0"
}

the "Manager" : switched from "0x186D154" to "0x186e154"
