### ISSUE TITLE
[BUG] EXP / Gold Tab & CS per min not working

### ISSUE THREAD

**Issue by challenger087** [floh22/LeagueBroadcastHub#24]
After your recent update EXP / Gold Tab & CS per min not working
[Log-2021-06-24-16-13.log](https://github.com/floh22/LeagueBroadcastHub/files/6710596/Log-2021-06-24-16-13.log)

**Comment by floh22** [comment]
Im currently working on a full remake of the frontend. The latest update may break some things until it is ready. This might take a week or two.

sorry for the inconvenience

**Comment by challenger087** [comment]
No problem
