### ISSUE TITLE
implement the herald and baron timers? [FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#240]
would you have any prediction of when it would be possible to implement the herald and baron timers?

and a fix for elder powerplay overriding elder drake's timer after no done, stay as override?

**Comment by overkido** [comment]
@floh22 @FFFFFFFXXXXXXX

**Comment by FFFFFFFXXXXXXX** [comment]
As far as i know @floh22 is almost completely inactive.
I am only familiar with a small part of the codebase so I wont be making any changes soon either.

So the current estimated time is never

**Comment by floh22** [comment]
Added in latest release
