### ISSUE TITLE
[BUG] Offsets updated, but gold not reading

### ISSUE THREAD

**Issue by UnifiedHyper** [floh22/LeagueBroadcastHub#242]
When I checked the logs to see what was causing the crash, it spit this out in response.
My offsets are updated, but it is continuing to spit out bad info.
[16-35-25] Init Team data
[16-35-25] [WARNING] Lux not found in memory snapshot. Values will be incorrect!
[16-35-25] [WARNING] Sequence contains no matching element
[16-35-25] [WARNING] Master Yi not found in memory snapshot. Values will be incorrect!
[16-35-25] [WARNING] Mordekaiser not found in memory snapshot. Values will be incorrect!

**Comment by EagleLOL** [comment]
{
  "OffsetVersion": "13.6.1",
  "GameOffsets": {
    "Manager": "0x186e154",
    "MapCount": "0x2c",
    "MapRoot": "0x28",
    "MapNodeNetId": "0x10",
    "MapNodeObject": "0x14"
  },
  "ObjectOffsets": {
    "ID": "0x8",
    "NetworkID": "0xb4",
    "Team": "0x34",
    "DisplayName": "0x54",
    "DisplayNameLength": "0x64",
    "Pos": "0x1dc",
    "Mana": "0x29c",
    "MaxMana": "0x2ac",
    "Health": "0xe7c",
    "MaxHealth": "0xe8c",
    "CurrentGold": "0x1bb4",
    "GoldTotal": "0x1bc4",
    "EXP": "0x32ec",
    "Name": "0x2b04"
  },
  "FileVersion": "1.0"
}

hey man this is the new file working. 
the "Manager" : switched from "0x186D154" to "0x186e154"

**Comment by UnifiedHyper** [comment]
That worked! Thanks a ton!
