### ISSUE TITLE
[BUG] Overlay not working, error windows pops up and after some time the program crashes

### ISSUE THREAD

**Issue by jazzMassive** [floh22/LeagueBroadcastHub#243]
So i went to edit my overlay a bit before a stream tommorrow, and this error popped up

![image](https://user-images.githubusercontent.com/60148417/227674026-8dbd1d5e-f487-422f-b2a0-2922b5944547.png)

A bit after that the overlay crashes.

Here are the logs:

https://pastebin.com/mu2pu9R7 (log)

https://pastebin.com/Uw3bPVgC (crash report)

**Comment by Welkick** [comment]
Hey, i have the same problem :(

**Comment by floh22** [comment]
offset issue
