### ISSUE TITLE
offsets bug, Urgent I have a championship final [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#244]
Urgent I have a championship final today can anyone help me

![image](https://user-images.githubusercontent.com/89580284/227773048-82ab9e22-0a8d-4ae1-811b-c87593d5ea60.png)

log crash:
[Crash-2023-03-26-08-28.log](https://github.com/floh22/LeagueBroadcast/files/11071443/Crash-2023-03-26-08-28.log)

**Comment by EagleLOL** [comment]
{
"OffsetVersion": "13.6.1",
"GameOffsets": {
"Manager": "0x186e154",
"MapCount": "0x2c",
"MapRoot": "0x28",
"MapNodeNetId": "0x10",
"MapNodeObject": "0x14"
},
"ObjectOffsets": {
"ID": "0x8",
"NetworkID": "0xb4",
"Team": "0x34",
"DisplayName": "0x54",
"DisplayNameLength": "0x64",
"Pos": "0x1dc",
"Mana": "0x29c",
"MaxMana": "0x2ac",
"Health": "0xe7c",
"MaxHealth": "0xe8c",
"CurrentGold": "0x1bb4",
"GoldTotal": "0x1bc4",
"EXP": "0x32ec",
"Name": "0x2b04"
},
"FileVersion": "1.0"
}

the "Manager" : switched from "0x186D154" to "0x186e154"

This file is in the config folder. You have to switch the "0x186D154" to "0x186e154". Everything else is the same. The file name is farsight.

**Comment by ManuelRoyBo** [comment]
This switch didn't work for me. Had to change  "0x186D154" to  "0x186f154"
