### ISSUE TITLE
[BUG] Crashing when ingame

### ISSUE THREAD

**Issue by Pefeci** [floh22/LeagueBroadcastHub#246]
Crashing when spectating game. Some farsight.json missing error even file is existing in folder.
Tried full reinstallation and some older versions all seem to crash.

On Windows 11 latest update to 03. April 2023

**Comment by FireFoXz09** [comment]
Have you tried this : 

https://github.com/floh22/LeagueBroadcast/issues/245

**Comment by floh22** [comment]
Duplicate
