### ISSUE TITLE
someone who knows how to pull the offsets [FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#248]
would it be possible for someone who knows how to pull the offsets to launch a video tutorial so that we can generate the offsets ourselves?

**Comment by Honzalis** [comment]
If that is possible to do that yourself that would be a huge help

**Comment by FireFoXz09** [comment]
Maybe you can find a bit of help here to do this : https://discord.com/channels/187652476080488449/1075755635544686705

This is a discord for third party apps for Riot Projects. There's a section about memory reading for League Broadcast and other similar tools. (created by Lars)

**Comment by Honzalis** [comment]
> Maybe you can find a bit of help here to do this : https://discord.com/channels/187652476080488449/1075755635544686705
> 
> This is a discord for third party apps for Riot Projects. There's a section about memory reading for League Broadcast and other similar tools. (created by Lars)

As far as I know you have to be a member of that server to read in that channel, can you share an invite link?

**Comment by FireFoXz09** [comment]
> > Maybe you can find a bit of help here to do this : https://discord.com/channels/187652476080488449/1075755635544686705
> > This is a discord for third party apps for Riot Projects. There's a section about memory reading for League Broadcast and other similar tools. (created by Lars)
> 
> As far as I know you have to be a member of that server to read in that channel, can you share an invite link?

My bad, here you go : https://discord.gg/riotgamesdevrel
