### ISSUE TITLE
[BUG] Crashes while spectating a live game only

### ISSUE THREAD

**Issue by Honzalis** [floh22/LeagueBroadcastHub#251]
Program crashes only when spectating live, ongoing game. When spectating a replay it ran fine. Logs show an error while loading a certain live event. Here are they
[Log-2023-04-19-02-13.log](https://github.com/floh22/LeagueBroadcast/files/11267318/Log-2023-04-19-02-13.log)
[Crash-2023-04-19-02-14.log](https://github.com/floh22/LeagueBroadcast/files/11267319/Crash-2023-04-19-02-14.log)

**Comment by Honzalis** [comment]
And as a new LOL patch rolled out, it loads and immediately crashes again :(
[Crash-2023-04-19-16-37.log](https://github.com/floh22/LeagueBroadcast/files/11274319/Crash-2023-04-19-16-37.log)

**Comment by FFFFFFFXXXXXXX** [comment]
LeagueBroadcast intentionally stops immediately in case it detects a live game running.

Quote from the README:

"League Broadcast uses Memory Reading to get information that the Riot API does not expose. Riot's policy in the past has been to allow passive memory reading, which is exactly what this program does, but this may change at any time. Use League Broadcast at your own risk. Anti Cheat does not ban for programs used during spectate, but it does however run while in a live game. Having League Broadcast open during a live (non-spectate) game may lead to account bans incase checks to stop it from running fail for some reason."

**Comment by Honzalis** [comment]
It worked in the past, at least for me with no issues. I consulted a riot representative in my country and they told me this as well but so far, riot does not ban this so why does it intentionally crash?

**Comment by Honzalis** [comment]
I consulted a Riot representative in my country in case Riot would have a problem with that and they have no problems with it. And in the past it worked. For us as a LOL championship creator this was crucial to be able to stream games with custom dynamic overlays while spectating them. And also the game that is being spectated is already 3 minutes delayed for our observer (tournament lobby), it does not make sense in my opinion to not allow it to run while spectating already delayed game.

**Comment by FFFFFFFXXXXXXX** [comment]
Nvm, now I understand what you mean.

I just tested spectating a tournament draft custom game with the not yet available new offsets and it works (at least for me).

So please wait for the offsets for the current patch to get added (that depends on when @floh22 finds the time to do it) and try after that.

**Comment by Honzalis** [comment]
Sorry if i expressed myself incorrectly in the issue title. My bad and thank you so much for working on this <3

**Comment by FFFFFFFXXXXXXX** [comment]
The new offsets are now available. Please try again and report back if something still doesnt work :)

**Comment by Honzalis** [comment]
Yep it works now, thank you

**Comment by Hexasiel** [comment]
> The new offsets are now available. Please try again and report back if something still doesnt work :)

I think there was a League Hotfix yesterday which messed up some of the Offsets. My spectate games are crashing (while replays are working just fine).
[Crash-2023-04-24-09-31.log](https://github.com/floh22/LeagueBroadcast/files/11307867/Crash-2023-04-24-09-31.log)

**Comment by Honzalis** [comment]
> > The new offsets are now available. Please try again and report back if something still doesnt work :)
> 
> I think there was a League Hotfix yesterday which messed up some of the Offsets. My spectate games are crashing (while replays are working just fine). [Crash-2023-04-24-09-31.log](https://github.com/floh22/LeagueBroadcast/files/11307867/Crash-2023-04-24-09-31.log)

I tried the spectate and the program is working fine for me. What offsets are you on? Just in case I have these set
[offsets.txt](https://github.com/floh22/LeagueBroadcast/files/11312688/offsets.txt)

or try downloading LB again and run the clean version of it

**Comment by FFFFFFFXXXXXXX** [comment]
@Hexasiel The current offsets are correct. I think you encountered some other bug from what I can guess from your crash log
