### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jonhdead3** [floh22/LeagueBroadcastHub#255]
Baron Issue timer not showing same as herald. Animation tho work. Any help? (drake time is working)

**Comment by FireFoXz09** [comment]
There's no timer for Baron or Herald at the moment programmed in the LeagueBroadcast. Only for dragons.

**Comment by Honzalis** [comment]
> There's no timer for Baron or Herald at the moment programmed in the LeagueBroadcast. Only for dragons.

Is it planned? It would have been amazing

**Comment by floh22** [comment]
Added in latest release
