### ISSUE TITLE
[BUG] Wrong offsets?

### ISSUE THREAD

**Issue by rapz** [floh22/LeagueBroadcastHub#259]
Hi i think we need to update the offsets

This help?

{
  "OffsetVersion": "13.10.1",
  "GameOffsets": {
    "Manager": "0x210ddc8",
    "MapCount": "0x48",
    "MapRoot": "0x40",
    "MapNodeNetId": "0x20",
    "MapNodeObject": "0x28"
  },
  "ObjectOffsets": {
    "ID": "0x10",
    "NetworkID": "0xc8",
    "Team": "0x3C",
    "DisplayName": "0x60",
    "DisplayNameLength": "0x70",
    "Pos": "0x280",
    "Mana": "0x340",
    "MaxMana": "0x358",
    "Health": "0x1068",
    "MaxHealth": "0x1080",
    "CurrentGold": "0x2148",
    "GoldTotal": "0x2160",
    "EXP": "0x4050",
    "Level": "0x4038",
    "Name": "0x38D0",
    "NameLength": "0x38E0"
  },
  "FileVersion": "1.0"
}

**Comment by chamorrorenzo** [comment]
NO :(

hopefully someone can make a video tutorial on how to get them and im sure I can get them everytime they update

**Comment by sdomi4** [comment]
Added new offsets, should work as intended now.

**Comment by rapz** [comment]
Still not working, here is the log

Log:
[Log-2023-05-25-15-21.log](https://github.com/floh22/LeagueBroadcast/files/11568088/Log-2023-05-25-15-21.log)

Crash Log:

[Crash-2023-05-25-15-24.log](https://github.com/floh22/LeagueBroadcast/files/11568140/Crash-2023-05-25-15-24.log)

**Comment by benholness** [comment]
We have a tournament tomorrow, would be really helpful if we had a stable version for this where it automatically updates the offsets without it crashing (seems to be a regular bug happening). I'm having the same issue with the new offsets created. I've also tried adding them in manually and still no luck.

Here are my logs:

Log:
[Log-2023-05-26-08-45.log](https://github.com/floh22/LeagueBroadcast/files/11572770/Log-2023-05-26-08-45.log)

Crash Log:
[Crash-2023-05-26-08-46.log](https://github.com/floh22/LeagueBroadcast/files/11572773/Crash-2023-05-26-08-46.log)

It looks like it might have something to do with this:

```
Time: 2023.05.26-08:56
Description: Error getting value from 'blueGold' on 'LeagueBroadcast.Ingame.State.StateData'.
```

**Comment by benholness** [comment]
It looks like it might have something to do with this:

Time: 2023.05.26-08:56
Description: Error getting value from 'blueGold' on 'LeagueBroadcast.Ingame.State.StateData'.

**Comment by sdomi4** [comment]
The stacktrace in the log by @benholness inidcates an issue with the EXP offset, and there might be a typo in there. Can you try changing `EXP` to `0x4020` locally and see if it works then?

**Comment by benholness** [comment]
@sdomi4 it works! thank you man :D just update your PR and I think we are golden

**Comment by sdomi4** [comment]
Updated the offsets to fix, should auto-update if I understood how it works correctly

**Comment by sod101316** [comment]
that's farsight.json offset right?

**Comment by benholness** [comment]
Yeah that's correct @sod101316, its that file that needs updating every new League of Legends patch.

**Comment by sod101316** [comment]
Where can I get the latest offset? Offsets in native-farsight-module have different contents.

**Comment by AzureAstral** [comment]
Anyone have a solution? Because on my side the offsets have not been updated and nothing works... We have a tournament tomorrow...

**Comment by s2candy2013** [comment]
@sdomi4  hello, do u have new offset? app crash when im join ingame
