### ISSUE TITLE
HUD IN GAME

### ISSUE THREAD

**Issue by alexissosa88** [floh22/LeagueBroadcastHub#26]
¿Alguien pudo cambiar el aspecto in game del score e info de oro, exp, ect? Ayuda!

**Comment by JoanJuan10** [comment]
Por ahora no, pero tengo entendido que en el futuro se podrá editar.

**Comment by cruxm4n** [comment]
what is your discord ? i can help you

**Comment by alexissosa88** [comment]
Ale-Sosa#5258 is my discord!

**Comment by floh22** [comment]
Closed due to inactivity
