### ISSUE TITLE
[BUG] Could not read champion data from memory 13.11

### ISSUE THREAD

**Issue by jazzMassive** [floh22/LeagueBroadcastHub#262]
![image](https://github.com/floh22/LeagueBroadcast/assets/60148417/490d9013-ab00-49af-b906-793dc61ea578)

This error started popping up again. Using the latest offsets aswell posted here.

[Log-2023-06-06-23-07.log](https://github.com/floh22/LeagueBroadcast/files/11669510/Log-2023-06-06-23-07.log)

**Comment by sdomi4** [comment]
Offsets should once again auto-update properly.
