### ISSUE TITLE
Baron/Herald Timer

### ISSUE THREAD

**Issue by jonhdead3** [floh22/LeagueBroadcastHub#266]
How can we add timer for baron and herald..
Over all how to change the timer look settings..
Any help will be appreciated.

**Comment by benholness** [comment]
Hey @jonhdead3, with in the program itself, you can enable the Baron and Elder timers in the Ingame settings panels (see screenshot).

<img width="963" alt="Capture" src="https://github.com/floh22/LeagueBroadcast/assets/28854222/923772a5-4cb6-49fe-8ef8-16010d4d20f9">

If you want to customise the look of the timers, you can go into the Config folder and open the Ingame.json file in a code editor. From there, you can adjust the BaronPowerPlay and ElderPowerPlay settings to your liking (it took me a bit of trial and error to see what setting does what, but if you save it whilst the program is running and refresh the source, it should update live for you). There's also DragonTimer settings if you have the dragon timer enabled.

Another neat thing you can do, which @floh22 told me about, is you can enable Dragon and Baron timers in the League Client itself (they are like the professional timers you see in the top left and right of the LCS and LEC broadcasts). All you need to do is go to Riot Games > League of Legends > Config and then open the game.cfg file. Once you've got it open in a code editor, add the line at the bottom of the file:

```
[Spectator]
eSportsNeutralTimers=1
```

<img width="202" alt="Capture2" src="https://github.com/floh22/LeagueBroadcast/assets/28854222/a01c48bb-f003-4bbb-a949-5412c9e46e77">

Once you restart the client and open a replay or spectate a game, you should see them appear 👍

Hope this helps! Happy casting!

**Comment by jonhdead3** [comment]
Thanks a lot. I have a last question I am facing 2 problems here first of all the icons are bugged for the drakes and there is not herald timer its only the baron 
![image](https://github.com/floh22/LeagueBroadcast/assets/129967662/389b0cbf-125b-4a11-ac19-a4f25ef51753)
as you can see.. Further more just asking so I know how to approach the situation I would like to have something like that 
![image](https://github.com/floh22/LeagueBroadcast/assets/129967662/b5ed4cf5-1194-4c22-be3d-bbcd3ad636ce)
Obviously not the same but like how can I achieve that should I check the program and customize the code or maybe use a third-party application in obs?
I appreciate a lot the help and I am looking forwards to your answer.
Have a great day!

**Comment by benholness** [comment]
> Thanks a lot. I have a last question I am facing 2 problems here first of all the icons are bugged for the drakes and there is not herald timer its only the baron ![image](https://user-images.githubusercontent.com/129967662/245469344-389b0cbf-125b-4a11-ac19-a4f25ef51753.png) as you can see.. Further more just asking so I know how to approach the situation I would like to have something like that ![image](https://user-images.githubusercontent.com/129967662/245469782-b5ed4cf5-1194-4c22-be3d-bbcd3ad636ce.png) Obviously not the same but like how can I achieve that should I check the program and customize the code or maybe use a third-party application in obs? I appreciate a lot the help and I am looking forwards to your answer. Have a great day!

No worries @jonhdead3! I think the icon not showing is a bug natively in the client (I know another bug Riot haven't fixed with their client 😅).

As for the herald timer, I don't think the client natively has that nor does this program so it might be a new feature that could be looked into. I'm not a direct contributor to this repo but someone might be able to look into this for you - I'm just a user like yourself I assume. Sorry that I can't be of much further help here.

**Comment by AzureAstral** [comment]
Up ! This is a good idea for Baron and Herald Timer !

**Comment by floh22** [comment]
Added in latest release
