### ISSUE TITLE
[BUG] Using the Reload button in OBS causes a crash

### ISSUE THREAD

**Issue by JoanJuan10** [floh22/LeagueBroadcastHub#27]
**Describe the bug**
Whenever you use the Reload button in OBS to reload the overlay in game, GOLD, EXP and CS/MIN graphs quit working and sometimes causes a crash

**To Reproduce**
1. Normal reproduce of a game, and suddenly it seems to freeze.
2. Reload the overlay
3. Execute either of the 3 graphs and won't work (The Gold diff graph works perfectly fine though)
4. Sometimes crashes

**Expected behavior**
I expected that it fixed itself and all the graphs working as expected.

**Material**
* If applicable, add screenshots to help explain your problem.
* Include Logs of when the error occured, as well as the crash log if applicable
* Please include the .rofl replay file if the issue was present while spectating

[Crash-2021-06-27-22-35.log](https://github.com/floh22/LeagueBroadcastHub/files/6722277/Crash-2021-06-27-22-35.log)
[Log-2021-06-27-18-43.log](https://github.com/floh22/LeagueBroadcastHub/files/6722279/Log-2021-06-27-18-43.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Last of Windows 10 (idk which)

**Comment by floh22** [comment]
What is your game language? If it is not english, can you try and see if setting your game language to english fixes the issue?
Can you send the .rofl replay file so I can see if it has anything to do with summoner names/champs/etc?

The error file seems to indicate it was having issues reading values anyway, but the gold graph is what crashed it, which is weird considering you said it was the only graph working

**Comment by JoanJuan10** [comment]
Here is the replay used and captures of the non expected behaviour before the crash

[Files.zip](https://github.com/floh22/LeagueBroadcastHub/files/6725297/Files.zip)

**Comment by floh22** [comment]
Side pages should be fixed in the latest update
