### ISSUE TITLE
[BUG] Software Crashing and Unable

### ISSUE THREAD

**Issue by Sigmna090** [floh22/LeagueBroadcastHub#273]
Software crashing shortly after launching spectate. Also having error message popup for Unable to load champion data and failed to load offset. 
![image](https://github.com/floh22/LeagueBroadcast/assets/117332147/3ef7a3ed-f169-4cd3-ae4b-d1cadb8f0d3d)

![image](https://github.com/floh22/LeagueBroadcast/assets/117332147/8574cf18-9bff-4530-8b75-25114952c417)

 - OS: Windows 11

[Crash-2023-07-07-13-56.log](https://github.com/floh22/LeagueBroadcast/files/11985120/Crash-2023-07-07-13-56.log)
[Log-2023-07-07-13-52.log](https://github.com/floh22/LeagueBroadcast/files/11985121/Log-2023-07-07-13-52.log)
[Log-2023-07-07-13-56.log](https://github.com/floh22/LeagueBroadcast/files/11985122/Log-2023-07-07-13-56.log)

**Comment by AzureAstral** [comment]
Offsets arent updated so the software didnt work ...

**Comment by sdomi4** [comment]
Offsets should once again auto-update properly.
