### ISSUE TITLE
[BUG] Baron Timer and CS/min bugged

### ISSUE THREAD

**Issue by TungVoidd** [floh22/LeagueBroadcastHub#274]
**Describe the bug**
So I just noticed a couple problems and don't know how to solve them. First of all the EXP, Gold and CS/min charts aren't working, it is displaying some random info. Second of all, when I activate the Baron Power Play, only the Baron image shows up, and when I turn it off, the gold and timer shows up

![image](https://github.com/floh22/LeagueBroadcast/assets/139003397/40e91a81-dd03-44f5-9e3f-d3654996da03)
In this example, the Baron Timer is turned off, but the box is still displayed
![image](https://github.com/floh22/LeagueBroadcast/assets/139003397/b9f8fcc4-1b26-46a7-b1f3-d2ae48f5c81f)
and this is it when it is turned on

![image](https://github.com/floh22/LeagueBroadcast/assets/139003397/cf6735d8-076e-4d7c-8b0d-e52f1af5e614)
Next, this is the same tab that appears when I press either the EXP, Gold or CS/min tab, and it only updates when I select the CS/min, Even so, I can't make sense of any of the numbers

**Comment by AzureAstral** [comment]
Same here for Baron Timer !
