### ISSUE TITLE
[BUG] Offsets

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#275]
Hey, offsets arent updated anymore, so how can i update them myself ? I searched but I'm not sure how to proceed. If anyone knows, it will help everyone to get the software working again.

**Comment by shinilee** [comment]
https://github.com/floh22/native-farsight-module

https://github.com/floh22/LeagueBroadcast/tree/v2/LeagueBroadcast.Farsight

I keep trying but it's been 3 month and I haven't figure out myself at all... I downloaded the reclass but the program itself doesn't even work and had to find crack reclass program and I can't even find out set location thing... I give up on it lol it's not really hurt me not to use leaguebroadcast program.

**Comment by sdomi4** [comment]
Offsets are updated, but only tested using the native module – I am not familiar with the LeagueBroadcast codebase, so not sure where the issue may be. Do you have any way to check which offsets you are using when encountering issues?

**Comment by shinilee** [comment]
> Offsets are updated, but only tested using the native module – I am not familiar with the LeagueBroadcast codebase, so not sure where the issue may be. Do you have any way to check which offsets you are using when encountering issues?

{
  "OffsetVersion": "13.13.1",
  "GameOffsets": {
    "Manager": "0x20d0e78",
    "MapCount": "0x48",
    "MapRoot": "0x40",
    "MapNodeNetId": "0x20",
    "MapNodeObject": "0x28"
  },
  "ObjectOffsets": {
    "ID": "0x10",
    "NetworkID": "0xc8",
    "Team": "0x3c",
    "DisplayName": "0x60",
    "DisplayNameLength": "0x70",
    "Pos": "0x220",
    "Mana": "0x340",
    "MaxMana": "0x358",
    "Health": "0x1058",
    "MaxHealth": "0x1070",
    "CurrentGold": "0x2118",
    "GoldTotal": "0x2130",
    "EXP": "0x3fe0",
    "Level": "0x3ff8",
    "Name": "0x3898",
    "NameLength": "0x38a8"
  },
  "FileVersion": "3.0"
}

this is the Offsets.

**Comment by sdomi4** [comment]
Are these the offsets obtained by the automatic update? They do not match the current [latest offsets](https://github.com/floh22/LeagueBroadcast/commit/35abf637b752093c65445d882cb5be8eda207987). I don't know how the updating mechanism works, so I might be adding the offsets wrong.

**Comment by shinilee** [comment]
> Are these the offsets obtained by the automatic update? They do not match the current [latest offsets](https://github.com/floh22/LeagueBroadcast/commit/35abf637b752093c65445d882cb5be8eda207987). I don't know how the updating mechanism works, so I might be adding the offsets wrong.

my bad I didn't check the latest offsets. once I manually update the offsets it works fine. I should of known... but, thank you. and sorry for the trouble.

**Comment by AzureAstral** [comment]
> S'agit-il des décalages obtenus par la mise à jour automatique ? Ils ne correspondent pas aux [derniers décalages](https://github.com/floh22/LeagueBroadcast/commit/35abf637b752093c65445d882cb5be8eda207987) actuels . Je ne sais pas comment fonctionne le mécanisme de mise à jour, donc j'ajoute peut-être mal les décalages.

But how did you manage to get the latest offsets?

**Comment by sdomi4** [comment]
I keep offsets up to date for another project and also update the offsets here. It looks like I was doing something wrong with the FileVersion parameter, autoupdates might now work again?

**Comment by AzureAstral** [comment]
It still does not work. When did you update them?

![Capture d’écran 2023-07-16 162914](https://github.com/floh22/LeagueBroadcast/assets/82313405/2826d497-dd82-4861-82a3-e8ca6a599821)

**Comment by sdomi4** [comment]
I usually update offsets on patchday, although I only fixed the FileVersion just now. I will update offsets again on Wednesday, maybe it works then.

**Comment by shinilee** [comment]
no it's working fine yesterday I test it and it work. all you had to do just update the offsets manually yourself. sdomi4 updated the offsets and it work with his offsets

**Comment by AzureAstral** [comment]
> non ça marche bien hier je l'ai testé et ça marche. tout ce que vous aviez à faire était de mettre à jour manuellement les décalages vous-même. sdomi4 a mis à jour les décalages et cela fonctionne avec ses décalages

It doesn't work for me, how did you do it? What offsets did you set manually?

**Comment by AzureAstral** [comment]
> no it's working fine yesterday I test it and it work. all you had to do just update the offsets manually yourself. sdomi4 updated the offsets and it work with his offsets

It doesn't work for me, how did you do it? What offsets did you set manually? I have all the time this error

**Comment by shinilee** [comment]
> > no it's working fine yesterday I test it and it work. all you had to do just update the offsets manually yourself. sdomi4 updated the offsets and it work with his offsets
> 
> It doesn't work for me, how did you do it? What offsets did you set manually? I have all the time this error

https://github.com/floh22/LeagueBroadcast/commit/35abf637b752093c65445d882cb5be8eda207987

here is the offsets from sdomi4 I just copy and pasted it

**Comment by AzureAstral** [comment]
I download and update again, and now it's work ! U think for the 13.14 patch the software will be down again or not ? :/

**Comment by sdomi4** [comment]
I can't guarantee that I always find the time on patch day, but shouldn't take more than a day or two

**Comment by sdomi4** [comment]
Updates for 13.14 are done – @AzureAstral can you confirm auto updates work as well?

**Comment by AzureAstral** [comment]
> Updates for 13.14 are done – @AzureAstral can you confirm auto updates work as well?

I'ill check tomorrow ;)

**Comment by AzureAstral** [comment]
Yes it's up to date !

{
  "OffsetVersion": "13.14.1",
  "GameOffsets": {
    "Manager": "0x2171660",
    "MapCount": "0x48",
    "MapRoot": "0x40",
    "MapNodeNetId": "0x20",
    "MapNodeObject": "0x28"
  },
  "ObjectOffsets": {
    "ID": "0x10",
    "NetworkID": "0xc8",
    "Team": "0x3c",
    "DisplayName": "0x60",
    "DisplayNameLength": "0x70",
    "Pos": "0x220",
    "Mana": "0x340",
    "MaxMana": "0x358",
    "Health": "0x1058",
    "MaxHealth": "0x1070",
    "CurrentGold": "0x2138",
    "GoldTotal": "0x2150",
    "EXP": "0x3f88",
    "Level": "0x3fa0",
    "Name": "0x3838",
    "NameLength": "0x3848"
  },
  "FileVersion": "3.0"
}

GJ man and thx !!

**Comment by AzureAstral** [comment]
BUT the software crash when we start a game

**Comment by sdomi4** [comment]
Do you receive any errors from the crash?

**Comment by AzureAstral** [comment]
No, just crash with nothing. The software just close !

**Comment by sdomi4** [comment]
Is this related to #276? Anyone else seeing this issue?

**Comment by AzureAstral** [comment]
> Is this related to #276? Anyone else seeing this issue?

And he crash when te game started in english too :(

**Comment by AzureAstral** [comment]
New problem : Info Page EXP dont work, he show CS/MIN :(

**Comment by AzureAstral** [comment]
> No, just crash with nothing. The software just close !

This is solved it’s my fault !

**Comment by sdomi4** [comment]
> New problem : Info Page EXP dont work, he show CS/MIN :(

Please open a new issue for this or add it to an existing issue with the same problem

**Comment by AzureAstral** [comment]
Someone have the new offsets ? RIOT make an update during the night....
