### ISSUE TITLE
[BUG] Install path

### ISSUE THREAD

**Issue by MrToWy** [floh22/LeagueBroadcastHub#28]
![image](https://user-images.githubusercontent.com/44198402/123680871-76aa0c00-d849-11eb-99f8-2e6aba65c262.png)

I think LeagueBroadcastHUB is having an issue with my installation path.

This is the path of my LoL.exe:
A:\Spiele\Riot Games\Valorant\League of Legends\LeagueClient.exe

This is what I've added to the config-file:

"LeagueInstall": [
      "C:\\",
      "D:\\",
      "E:\\",
      "A:\\",
      "C:\\Program Files",
      "C:\\Program Files (x86)",
      "A:\\Spiele",
      "A:\\Spiele\\Riot Games",
      "A:\\Spiele\\Riot Games\\Valorant",
      "A:\\Spiele\\Riot Games\\Valorant\\League of Legends"
    ],

**Comment by floh22** [comment]
Try `A:\\Spiele` and see if that helps. Replace all `\` with `\\`

The Configs arent very user friendly at the moment, im sorry.

**Comment by MrToWy** [comment]
Oh, sry, that's what I've done, GitHub formatted it differently 😂 

![image](https://user-images.githubusercontent.com/44198402/123701943-c9dc8880-d862-11eb-827f-5f198fe12564.png)

**Comment by MrToWy** [comment]
A fix for me would be to move the game to another folder, but maybe others users have a similar path and the code should be fixed? 🤔

**Comment by floh22** [comment]
Next release should support you adding the League folder directly, so would only need to include 
`A:\\Spiele\\Riot Games\\Valorant\\League of Legends` in your case.

I did not expect people to have their game folder within another Riot Game folder. Guess that ones on me for assuming
