### ISSUE TITLE
[BUG] crash because update

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#281]
Yesterday the software works perfectly, and today i try again and he crash "Cant read data blabla"

...

RIOT make an update tonight u think it's that the problem ? i have an tournament today... It's a big problem... 

Solution ?

**Comment by AzureAstral** [comment]
maybe @floh22 or @sdomi4 u have an idea ?

**Comment by sdomi4** [comment]
https://github.com/floh22/LeagueBroadcast/blob/v2/Offsets/Offsets-13.14.2.json offsets are updated – If the autoupdate doesn't want to work set them manually (the only change should be the ObjectManager offset)

**Comment by AzureAstral** [comment]
It's ok !! Thx man !
