### ISSUE TITLE
[BUG] Cant read again

### ISSUE THREAD

**Issue by AzureAstral** [floh22/LeagueBroadcastHub#282]
This software bug again... Can't read data from blabla...

It's annoying T_T

@sdomi4

**Comment by sdomi4** [comment]
Offsets are correct and there hasn't been another update. Can you check you are receiving the correct offsets (13.4.2 with `"Manager": "0x21716E0"`)?

**Comment by AzureAstral** [comment]
Yes all is ok (now 13.15 is release so dont work) but with the good offsets i have an error

**Comment by sdomi4** [comment]
Offsets are updated for 13.15

**Comment by AzureAstral** [comment]
I have good offsets but... i have this message again and I double check offsets so here this is not the problem

![cant](https://github.com/floh22/LeagueBroadcast/assets/82313405/a58c6609-4387-4989-a657-a5b9edc1e00c)
