### ISSUE TITLE
gold not counting memory error [BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#290]
![image](https://github.com/floh22/LeagueBroadcast/assets/89580284/a388af44-d1a8-4b40-b753-86ab18f0756f)
![image](https://github.com/floh22/LeagueBroadcast/assets/89580284/155d2bee-15ff-465b-b2ef-865c91db4ba9)

Log.
[Log-2023-09-02-14-16.log](https://github.com/floh22/LeagueBroadcast/files/12504867/Log-2023-09-02-14-16.log)

**Comment by Walace4458** [comment]
Mano, vai na pasta FARSIGHT e muda pra esse offset aq, tava com o mesmo problema e isso resolveu o meu

{
  "OffsetVersion": "13.17.1",
  "GameOffsets": {
    "Manager": "0x2192e08",
    "MapCount": "0x48",
    "MapRoot": "0x40",
    "MapNodeNetId": "0x20",
    "MapNodeObject": "0x28"
  },
  "ObjectOffsets": {
    "ID": "0x10",
    "NetworkID": "0xC8",
    "Team": "0x3C",
    "DisplayName": "0x60",
    "DisplayNameLength": "0x70",
    "Pos": "0x220",
    "Mana": "0x340",
    "MaxMana": "0x358",
    "Health": "0x1058",
    "MaxHealth": "0x1070",
    "CurrentGold": "0x2138",
    "GoldTotal": "0x2150",
    "EXP": "0x3F88",
    "Level": "0x3FA0",
    "Name": "0x3838",
    "NameLength": "0x3848"
  },
  "FileVersion": "3.0"
}

**Comment by Walace4458** [comment]
pelo q eu vi no dc oq falaram pra mim e pq o automatico buga ai tem q sempre vir aq e pegar manualmente pra fazer funcionar

**Comment by overkido** [comment]
> pelo q eu vi no dc oq falaram pra mim e pq o automatico buga ai tem q sempre vir aq e pegar manualmente pra fazer funcionar

eu excluir meu arquivo e abrir o app novamente, pra baixar e troquei as letras minúscula por maiúscula e funciono .
