### ISSUE TITLE
[BUG] 1.4.2

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#30]
Thank you for this huge update I love it!!

I'm still testing right now but I will keep add if I found new bug

"ItemComplete"
BUG 1. if I change "ShowOnScoreboard" to True it doesn't show on scoreboard
BUG 2. ShowItemName : true, the mask only work on Blue Side (Left), Red Side the mask doesn't work

"ObjectiveKill"
BUG 3. If I change UseVideo to True the Video showing only 1 to 2 sec

**Comment by floh22** [comment]
1. I have not added scoreboard yet. I will have to add proper documentation for what works, what doesnt, and how.
3. `ForceDisplayDurationForVideo = true` should make the video play for its entire duration, otherwise the duration set by `DisplayDuration` will be used

**Comment by shinilee** [comment]
> 1. I have not added scoreboard yet. I will have to add proper documentation for what works, what doesnt, and how.
> 2. `ForceDisplayDurationForVideo = true` should make the video play for its entire duration, otherwise the duration set by `DisplayDuration` will be used

Thank you for quick replay

it's set as true for ForceDisplayDurationForVideo but it play 1 to 2 sec and goes away :(

and Found the new bug for teamcolor

if I change ingame.json file
I change the Circle Color "UseTeamColor" to false and if I change the score from LeagueBroadcast program the color goes back to team color

nvm for the UseTeamColor it's working now it stay the color I choose from

**Comment by shinilee** [comment]
https://youtu.be/JPPmihaAdNI?t=984

CS/min working fine
Player Gold working fine
EXP per player

missing 2 people avatar

https://youtu.be/JPPmihaAdNI?t=1370

Item Finish offset is higher then Player Gold

**Comment by shinilee** [comment]
hey I just want to make sure this is you

![image](https://user-images.githubusercontent.com/82671596/125297410-33de3e80-e2f5-11eb-9a62-dd1ed2138e2a.png)

**Comment by floh22** [comment]
Yes that is me, thanks for confirming

**Comment by floh22** [comment]
Both champ indicators and indicator height fixed in latest commits
