### ISSUE TITLE
Could not read all champion data from memory. Please submit an issue on github containing the current log and replay. [BUG]

### ISSUE THREAD

**Issue by FKLevi1** [floh22/LeagueBroadcastHub#303]
**Describe the bug**
Whenever I try to spectate a game, I get this problem.

**To Reproduce**
1. Go to 'League Broadcast'
2. Click on 'League Broadcast'
4. See error "Could not read all champion data from memory. Please submit an issue on github containing the current log and replay. "
**Expected behavior**
Run and pick the data properly but gold and everything else doesn't work

**Material**
![image](https://github.com/floh22/LeagueBroadcast/assets/96711047/74a6b118-cdf8-4c17-abdf-a02b55e8e1b1)

Logs: 
[Log-2023-10-29-12-37.log](https://github.com/floh22/LeagueBroadcast/files/13197448/Log-2023-10-29-12-37.log)
[Log-2023-10-29-13-17.log](https://github.com/floh22/LeagueBroadcast/files/13197449/Log-2023-10-29-13-17.log)
[Log-2023-10-29-13-18.log](https://github.com/floh22/LeagueBroadcast/files/13197450/Log-2023-10-29-13-18.log)
[Log-2023-10-29-13-26.log](https://github.com/floh22/LeagueBroadcast/files/13197453/Log-2023-10-29-13-26.log)

**Desktop: **
 - OS: [e.g. Windows 10] (All up to date)
 - Version [e.g. 20H1 (May 2020 Update) Build 19041] (All up to date)
 
![image](https://github.com/floh22/LeagueBroadcast/assets/96711047/19a9e83e-3d33-40ba-9313-c5443a892e54)

**Additional context**
I don't have any clue on how to fix this issue. If someone could please guide me through it, it would be very helpful. I have seen in past posts something about offsets

**Comment by sdomi4** [comment]
Should be fixed with [updated offsets](https://github.com/floh22/LeagueBroadcast/commit/c76e8f82cbe125720b8aa70cedf251dcb8da34fe#diff-48b16cc9292512ee756eca2f0ff3476b72cc5ef140c059bef8673d6186b2cbb2), there was a hotfix.

**Comment by FKLevi1** [comment]
> Should be fixed with [updated offsets](https://github.com/floh22/LeagueBroadcast/commit/c76e8f82cbe125720b8aa70cedf251dcb8da34fe#diff-48b16cc9292512ee756eca2f0ff3476b72cc5ef140c059bef8673d6186b2cbb2), there was a hotfix.

How do I do that? Can you please guide me step by step??

**Comment by FKLevi1** [comment]
> Should be fixed with [updated offsets](https://github.com/floh22/LeagueBroadcast/commit/c76e8f82cbe125720b8aa70cedf251dcb8da34fe#diff-48b16cc9292512ee756eca2f0ff3476b72cc5ef140c059bef8673d6186b2cbb2), there was a hotfix.

Please provide me the hotfix

**Comment by sdomi4** [comment]
The updated offsets for the hotfix are in the link above.
In theory, LeagueBroadcast should automatically update to the newest offsets. If it's still crashing with the same error message, manually change the `"Manager"` value in `Farsight.json` to `0x21D9220`
