### ISSUE TITLE
viego makes item purchase animation activate + top and bot inhbs timers are switched 

### ISSUE THREAD

**Issue by VortexHD96** [floh22/LeagueBroadcastHub#31]
whenever vigeo takes someone died champ he makes all items show up in item purchase animation 
top and bot inhbs timers are switched 
all can be seen in screenshot
![125146350-b0babe00-e125-11eb-8ef0-9f4b66a8b062](https://user-images.githubusercontent.com/87213159/125146437-1a3acc80-e126-11eb-9e31-7e4afd4fff3b.png)

**Comment by shinilee** [comment]
I fixed the inhib by switch the lane icon name top and bot
