### ISSUE TITLE
[BUG] Small Bugs That I Found

### ISSUE THREAD

**Issue by ForsakenCAAF** [floh22/LeagueBroadcastHub#32]
Hey! So I've been messing around with the tool and here are some of the bugs I have found:

1. Senna CSPM - For some reason it is counting her souls as CS in an abnormal way (roughly 0.2 per soul she catchs on the ground), and thus she actually gets insanely high CSPM, saw one that was regular farming plus catching some random souls on the ground and was with 11.2 CSPM with only 82 cs at 11 minutes, give or take.

2. Item Names on Red Side - The background is on a top layer for Red Side Icons. Thus when the name/background pops up, it covers the little circle ultimate thing. It doesn't seem to happen on the blue side.

3. Baron Power Play and Soul Animation Video - For some reason, when I try to use the video animation it gets offset really bad and the animation is coming off switched (Shows up out of nowhere and then it repeats twice, coming up and then down). Not entirely sure why yet, but it doesn't happen with the image.

4. Baron Power Play, Soul and Inibitors Image - If I speed up the replay or spectator, the pop up comes with a delay, depending on how much time I skipped over. Also sometimes it skips over the whole Baron or Dragon warning, regardless if I speed up or not, and I still couldn't figure out why. Sometimes it shows, other times it doesn't. It doesn't seem to affect the timer on the top right at all tho.

5. Top Right Timer gets locked after it finishes - The timer seems to disappear for a while after the baron buff expires, but then it comes back and it's locked at 00:00 and the gold difference that was left at. I expected it to just disappear and say the timer until the next baron again. Because of this, when the Baron is done a second time, the timer overlay just disappears and we're only left with the Baron Icon.

6. Elder Dragon Timer - It seems like there are settings for it, but it doesn't show up. The notification did show up, aswell as the Icon on the top left. But the timer or gold difference doesn't until the buff as actually expired. When it expires it shows 00:00 and the Gold Difference gotten. It only happened once so far because I only got to spectate one game with Elder Dragon.

7. Level Up over Stats - I think someone else already talked about this, but just to be sure I'm not missing anything. When the stats overlay is showing, it seems like the level up animation is on the top layer and goes over it. It doesn't seem to happen with items, so I'm not sure which one is intended here.

8. Soul Point Warning too early - Again, not sure if this is intended, but it seems like the Soul Point warning comes up when, and only when, the first team reachs the 3rd drake. Shouldn't it only be when one of them actually gets the Soul (4th drake)? Asking this because otherwise it would make sense to show Soul Point to both teams instead when they get to their own 3rd drake.

I'm using Windows 10 with all the latest updates.

I think some of the problems with Dragon Timers, Inibitors, etc are solved with me messing with OBS and setting the properties of the Browser Source to refresh when the source becomes active, but there should be a better way of doing it no? Like constantly refreshing? Thanks for the great job!

**Comment by floh22** [comment]
All except Elder Dragon Timer confirmed and fixed in latest commit 6ebb8c93aa0c5dd3bdd9d8c5093f05b399f458a7

Elder Drake Timer could not be reproduced, needs further testing
