### ISSUE TITLE
IDIOMA

### ISSUE THREAD

**Issue by alexissosa88** [floh22/LeagueBroadcastHub#34]
¿Se puede cambiar a español los items e información in game?

**Comment by JoanJuan10** [comment]
No lo tengo claro, debería mirarmelo pero tengo mis dudas.

(Clarification for English: He is asking if the items names and other info could be translated into Spanish.)

**Comment by floh22** [comment]
Item names should be shown in the game language. Once memory works in different languages, they will automatically update.
As for other texts, language support is something that I have not added yet, though may do so in the future
