### ISSUE TITLE
[BUG] Bugs with the replay

### ISSUE THREAD

**Issue by ForsakenCAAF** [floh22/LeagueBroadcastHub#39]
**Bugs:**

**1.** _Basically when you go back in time, during the replay the dragon count doesn't, meaning you can get an infinite number of dragons._

**2.** _If you spectate a game while it is already going, the kill and dragon count starts as zero in the Score Display HUD, as if the game is just starting._

**To Reproduce:**

**1.** _Let dragon be made. Retrocede a few seconds, let it be made again. Team basically gets 2 dragons, when in the game they should only have 1._

**2.** _Spectate any game that's already going on._

**Expected:**

**1.** _Dragon capture to retrocede aswell._

**2.** _The HUD to show the actual kills and dragons._

**Desktop:**

Windows 10, latest update.

**Comment by floh22** [comment]
2. sadly cannot be fixed as these values are not read from memory but rather events are captured from the LiveEvents API, so it cannot capture events that have already happened in the past

**Comment by ForsakenCAAF** [comment]
Oh, that's unfortunate!

**Comment by floh22** [comment]
The only way that gets fixed is if some esports org ever pays me to make a full memory reading version that is compatible with tournament realm, so its rather unlikely.

A couple features just dont work when you dont follow the standard gameflow. CS, Timers, Kills, Towers, Drakes come to mind

**Comment by ForsakenCAAF** [comment]
I wish you luck with that, there might be someone out there interested and capable of paying. You're doing something great over here.

**Comment by Pwnedev** [comment]
@floh22 Do you have access to the in-game time? That could solve all those issues
