### ISSUE TITLE
app se cierra al iniciar sesión

### ISSUE THREAD

**Issue by alexissosa88** [floh22/LeagueBroadcastHub#46]
*alguna solución donde no abre la app, carga y automáticamente se cierra

**Comment by floh22** [comment]
Please create issues in english so both I and others on the git can understand the issue

**Comment by JoanJuan10** [comment]
I reopen this to translate this message:

"Any fix where the app doesn't open, it loads but then it automatically closes"

`Disclaimer: I am only translating this so we all can understand, I am not submiting this as an issue that happens to myself either.`

**Comment by alexissosa88** [comment]
After the update, when you open the application it closes at the moment without being able to select anything, any solution?
