### ISSUE TITLE
APP NOT RUN

### ISSUE THREAD

**Issue by alexissosa88** [floh22/LeagueBroadcastHub#47]
After the update, when you open the application it closes at the moment without being able to select anything, any solution?

**Comment by floh22** [comment]
Please provide logs and crash logs so I can see what is happening.
It would be best if you set LogLevel = 3 in Component.json config so logging shows more

**Comment by alexissosa88** [comment]
can I communicate by some direct channel with you to show you a video, why do I not understand? discord?

**Comment by floh22** [comment]
you can send me a video via twitter. its linked in this git.

Otherwise, im guessing I know what happened and this should not be an issue anymore.
