### ISSUE TITLE
[BUG] Start of a spectated game, replay or live and it Crashes

### ISSUE THREAD

**Issue by JoanJuan10** [floh22/LeagueBroadcastHub#48]
**Describe the bug**
The app crashes whenever I start spectating a live game or I start a replay (In the case of replays, it even crashes league of legends)

**To Reproduce**
1. Turn on Essence (Client Connected)
2. Spectate a Live Game
3. Crash occurs

1. Start a replay
2. Whenever the game start and some time elapses, it sometimes crashes.

**Expected behavior**
It should not crash and work as expected, as before the last update.

**Material**
Crash Logs:
[Crash-2021-07-21-19-26.log](https://github.com/floh22/LeagueBroadcast/files/6857799/Crash-2021-07-21-19-26.log)
[Crash-2021-07-21-19-34.log](https://github.com/floh22/LeagueBroadcast/files/6857800/Crash-2021-07-21-19-34.log)

Logs:
[Log-2021-07-21-19-14.log](https://github.com/floh22/LeagueBroadcast/files/6857803/Log-2021-07-21-19-14.log)
[Log-2021-07-21-19-33.log](https://github.com/floh22/LeagueBroadcast/files/6857804/Log-2021-07-21-19-33.log)
[Log-2021-07-21-19-34.log](https://github.com/floh22/LeagueBroadcast/files/6857805/Log-2021-07-21-19-34.log)

**Desktop (please complete the following information):**
 - Windows 10
 
 **Additional Information**
It may be unrelated but the spectator, seems to also crash whenever I put the mouse over the timeline of the game.

**Comment by floh22** [comment]
Can you send me the replay file you used?
I have a theory but no good way to test it without the specific replay

**Comment by JoanJuan10** [comment]
Okay. I will send it.

[EUW1-5378141950.zip](https://github.com/floh22/LeagueBroadcast/files/6870605/EUW1-5378141950.zip)

**Comment by floh22** [comment]
Just watched the full game with both exp tab and gold graph open without issue.
Does it crash for you every time you open the game?

**Comment by JoanJuan10** [comment]
> Just watched the full game with both exp tab and gold graph open without issue.
> Does it crash for you every time you open the game?

The issue has not to do with either of those graphs. The issue is that when the mouse hovers on the timeline of the replay, it makes the replay crash.
When having the program not started, it doesn't crash neither causes any problems.

**Comment by floh22** [comment]
if the game crashes while you do something in game, that isnt a problem with this. Seems like a patch/installation/PC issue.

Cannot reproduce
