### ISSUE TITLE
[BUG] Custom color from teams won't load when you restart the program

### ISSUE THREAD

**Issue by FireFoXz09** [floh22/LeagueBroadcastHub#62]
**Describe the bug**
When you close or restart the League Broadcast program, The Color Pick reset to the default blue / red color, even if in the TEAM.json files, the custom rgb is saved with the correct color.

**To Reproduce**
1. Open League Broadcast
2. Click on Pick Ban (on the left menu)
3. Select a Custom Color for your team.
4. Save your team (with the "+" button on the top of the team)
5. Close League Broadcast
6. Re-Open League Broadcast
7. The Custom Color have reset to the blue/red color

**Expected behavior**
The Color Pick shoud load the color you saved for a precise team.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version 10.0.19042
 
 ![image](https://user-images.githubusercontent.com/89284738/130328145-18446ce2-e688-46c4-ab25-1d1ece233384.png)

**Comment by floh22** [comment]
This is mostly the result of team colors being something I added, then later changed how they work to make side specific colors easier to use. I will probably fix this at some point, but for now, colors are side specific instead of team specific
