### ISSUE TITLE
> Idem Problem

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#65]
bug in app, gold doesn't work, pops level item, spawn can someone help, and who can help fix bug.
![image](https://user-images.githubusercontent.com/89580284/130948325-eb4796f8-aa5c-4e1b-84ee-aa306a76e5e7.png)

> Idem Problem
what is that mean Idem Problem?
_Originally posted by @shinilee in https://github.com/floh22/LeagueBroadcast/issues/64#issuecomment-906084774_

**Comment by floh22** [comment]
Should be fixed
