### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#66]
where changes the left bd of dragon elder that personaliser but uses nashon msm and not bdleft
![image](https://user-images.githubusercontent.com/89580284/130951801-a6c040eb-b38c-4f27-ad00-e1c817dcb11b.png)

the bg of the left I want for this but it doesn't change the same as baron nashon.
![image](https://user-images.githubusercontent.com/89580284/130952357-3a381d1f-39e3-46a5-96a3-ed390080f24a.png)

my goals also spawn and kill doesn't work normally only soul dragon point and baron powerplay.

gold does not count due to initial error as soon as replay opens.
![image](https://user-images.githubusercontent.com/89580284/130952844-2eb66ccc-59bc-4cb1-a0f1-86d71e605ead.png)

**Comment by alexissosa88** [comment]
voce tiiene discord OVERIKDO?

**Comment by overkido** [comment]
Sim chama lá. 
![image](https://user-images.githubusercontent.com/89580284/131015857-a046274c-8499-408b-9027-d101c2ceac86.png)

**Comment by alexissosa88** [comment]
Ale-Sosa#5258 Add me no encontro

**Comment by floh22** [comment]
Values being wrong should be fixed.

As for the first part, the left indicator, so drake, only works when Elder is taken, since I did not think a normal dragon power play makes much sense, only for elder/baron. So when Elder is taken, the left indicators will be used

**Comment by alexissosa88** [comment]
> Sim chama lá.
> ![image](https://user-images.githubusercontent.com/89580284/131015857-a046274c-8499-408b-9027-d101c2ceac86.png)

no logro encontrar :(

**Comment by overkido** [comment]
Chama no Twitter ou Instagram.
Twitter: @IagolMoura,
Instagram: @iagomouraof

**Comment by overkido** [comment]
> Values being wrong should be fixed.
> 
> As for the first part, the left indicator, so drake, only works when Elder is taken, since I did not think a normal dragon power play makes much sense, only for elder/baron. So when Elder is taken, the left indicators will be used

that's when he does it himself, he doesn't use the image of the elder I made, but the same as the baron, I want to know if there's a way to change it to not use the msm of the baron but the one of the bgleftelder.

**Comment by overkido** [comment]
> Values being wrong should be fixed.
> 
> As for the first part, the left indicator, so drake, only works when Elder is taken, since I did not think a normal dragon power play makes much sense, only for elder/baron. So when Elder is taken, the left indicators will be used

![image](https://user-images.githubusercontent.com/89580284/131032472-a6e25533-03ec-4820-9094-9e21d2a51c45.png)

elder's bg doesn't stay, he keeps the baron's power play bg, i want to know if there's a way to modify only the elder's when it's done and stays there on the left to keep the bg i made for elder.

![image](https://user-images.githubusercontent.com/89580284/131032507-e22f6f52-23d4-404a-bcfa-32b2f556dc20.png)

the baron's bg is the one in graphite almost black, the elder's is graphite with green.

![image](https://user-images.githubusercontent.com/89580284/131032530-95049d2d-0636-4a4a-95f8-15ddef53da8d.png)

as you can see here in the image there is baron nashon's bd and dragelder's, but in the game in the transmission only baron's is left.

**Comment by overkido** [comment]
I don't know if there's how, but would it be possible to put the drags and herald timer and put the baron's arautop in the league broudcast layout?, to remove this one from riot that puts in the game?, to customize the text and the timer image too like the one from lck that when he makes a baron he gets power play on the side of the team he made.

![image](https://user-images.githubusercontent.com/89580284/131033615-91a81448-8198-4b1b-8484-5ebab84c2af4.png)

**Comment by daisukedd** [comment]
Overkido adiciona no discord 𝗱𝗮𝗶𝘀𝘂𝗸𝗲#0132, segui você no twitter, gostaria de trocar um papo e conversar sobre a HUD.

**Comment by overkido** [comment]
> Overkido adiciona no discord 𝗱𝗮𝗶𝘀𝘂𝗸𝗲#132, segui você no twitter, gostaria de trocar um papo e conversar sobre a HUD.

manin não achei não seu discord chama no twitter

**Comment by overkido** [comment]
174 / 5000
Resultados da tradução
what i said about using the same image in baron and elder was that about power play uses msm i did it based on the contents of the folder that had the left objective and it doesn't change .

![image](https://user-images.githubusercontent.com/89580284/131144241-b0d052af-9f33-451d-9726-e3bded0188b8.png)

**Comment by FireFoXz09** [comment]
> > Values being wrong should be fixed.
> > As for the first part, the left indicator, so drake, only works when Elder is taken, since I did not think a normal dragon power play makes much sense, only for elder/baron. So when Elder is taken, the left indicators will be used
> 
> ![image](https://user-images.githubusercontent.com/89580284/131032472-a6e25533-03ec-4820-9094-9e21d2a51c45.png)
> 
> elder's bg doesn't stay, he keeps the baron's power play bg, i want to know if there's a way to modify only the elder's when it's done and stays there on the left to keep the bg i made for elder.
> 
> ![image](https://user-images.githubusercontent.com/89580284/131032507-e22f6f52-23d4-404a-bcfa-32b2f556dc20.png)
> 
> the baron's bg is the one in graphite almost black, the elder's is graphite with green.
> 
> ![image](https://user-images.githubusercontent.com/89580284/131032530-95049d2d-0636-4a4a-95f8-15ddef53da8d.png)
> 
> as you can see here in the image there is baron nashon's bd and dragelder's, but in the game in the transmission only baron's is left.

Maybe because you misnamed the picture? You need to name it ObjectiveBGLeft and not ObjectiveBGElder I think?

**Comment by overkido** [comment]
> "Maybe because you misnamed the picture? You need to name it ObjectiveBGLeft and not ObjectiveBGElder I think?"

no I changed the name in the image and changed it in main.js, to see if the image changed but it doesn't change it keeps the baron's bg
