### ISSUE TITLE
[BUG] inhibitor

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#68]
it won't hide after time out

**Comment by overkido** [comment]
the emu isn't hiding either

**Comment by overkido** [comment]
mine isn't hiding either, and when you put a custom image, the image doesn't appear

**Comment by FireFoXz09** [comment]
Samething here, custom images have trouble to load with the inhibitor timer AND the gold graph pop-up.

Also, if an inhibitor respawn, it's won't hide, but if in the meantime (while all inhib are alive/up) another inhibitor is destroyed, the League Broadcast crash and close.

**Comment by floh22** [comment]
Can you post crash logs and logs when this issue happens? 

As for it not hiding, that has been a problem for some time and so far I have not been able to find the root of the issue.
I am working on a rewrite and hope that will solve this

**Comment by overkido** [comment]
on the inhibitor it would be possible to change the side of the inhibitors, the blush has the inhibitors only from the blush, and the redside the inhibitor timer is above the minimap?

**Comment by floh22** [comment]
> on the inhibitor it would be possible to change the side of the inhibitors, the blush has the inhibitors only from the blush, and the redside the inhibitor timer is above the minimap?

This is a separate issue.

Original issue fixed in latest release
