### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#69]
the broadcast is crashing when the gold chart opens and closes.

how to fix, and how to increase the source of graphic gold?

**Comment by floh22** [comment]
Please provide logs and crash logs when the crash occurs.

As for increasing source of graphic gold, im not quite sure what you mean by that. You can resize almost all elements of the frontend through in ingame.json file

**Comment by overkido** [comment]
how to increase the font of the golden chart, in ingame.json in font/size: it's not increasing the font size

**Comment by overkido** [comment]
![image](https://user-images.githubusercontent.com/89580284/132713932-24785a00-cb18-421e-a8fb-5dd63b6e2fb0.png)

how to increase the font of the golden chart, in ingame.json in font/size: it's not increasing the font size

**Comment by floh22** [comment]
save the file and reload the webpage, I forgot to add auto update for these values

**Comment by FireFoXz09** [comment]
I can say that the STYLE, NAME, and COLOR works, but the ALIGN and the SIZE option don't change anything, even when I refresh the browser or reset the app. 

Just to be clear, I' m guessing it's supposed to change the numbers font on the gold graph.

**Comment by overkido** [comment]
yes it is the gold numbers of the teams that do not increase, increases the size of the graph and talal but the text is small does not increase.

> I can say that the STYLE, NAME, and COLOR works, but the ALIGN and the SIZE option don't change anything, even when I refresh the browser or reset the app.
> 
> Just to be clear, I' m guessing it's supposed to change the numbers font on the gold graph.

yes it is the gold numbers of the teams that do not increase, increases the size of the graph and talal but the text is small does not increase.

**Comment by floh22** [comment]
closing as crash seems to be resolved
