### ISSUE TITLE
the pick and ban iu does not work

### ISSUE THREAD

**Issue by ihabdz55** [floh22/LeagueBroadcastHub#70]
hi guys i followed these steps
- Download latest release
- Unzip release to desired install folder
- Add http://localhost:9001/frontend?backend=localhost as a browser source in OBS in your ingame scene
Add http://localhost:9001/?backend=ws://localhost:9001/api as a browser source in OBS in your PickBan scene

everything works fine but the last step the pick ban scene when i start a champ select nothing happens  should i do something ? 
didn't understand that part plz help

**Comment by floh22** [comment]
Can you post logs when this issue occurs?

**Comment by ihabdz55** [comment]
yes but i don't  know  how or where to find the logs

**Comment by ihabdz55** [comment]
[Log-2021-09-08-15-39.log](https://github.com/floh22/LeagueBroadcast/files/7129703/Log-2021-09-08-15-39.log)
here is the log sir

**Comment by floh22** [comment]
mind posting the crash log as well?

**Comment by ihabdz55** [comment]
[Crash-2021-09-08-15-40.log](https://github.com/floh22/LeagueBroadcast/files/7129852/Crash-2021-09-08-15-40.log)
[Crash-2021-09-08-15-43.log](https://github.com/floh22/LeagueBroadcast/files/7129853/Crash-2021-09-08-15-43.log)
[Crash-2021-09-08-15-52.log](https://github.com/floh22/LeagueBroadcast/files/7129854/Crash-2021-09-08-15-52.log)
yes

**Comment by ihabdz55** [comment]
also when the champ select ends the app closes and i need to start it again once i'm in the game

**Comment by ihabdz55** [comment]
[Log-2021-09-08-19-17.log](https://github.com/floh22/LeagueBroadcast/files/7131025/Log-2021-09-08-19-17.log)
here is the log 
and here is the crash logs when i enter champ select nothing happens and the programm crash 

[Crash-2021-09-08-19-19.log](https://github.com/floh22/LeagueBroadcast/files/7131027/Crash-2021-09-08-19-19.log)

**Comment by ihabdz55** [comment]
f
