### ISSUE TITLE
[BUG] Pick and ban  not responding

### ISSUE THREAD

**Issue by markos10l** [floh22/LeagueBroadcastHub#73]
**Describe the bug**
the Pick and Ban phase not responding 

**To Reproduce**
1. Go to 'strat league of legends client'
2. Click on 'create a custom game and start the pick and ban phase'
3. Scroll down to 'start  banning and picking champs '

**Expected behavior**
when i go to http://localhost:9001/?backend=ws://localhost:9001/api  i should see the picks and bans .

**Material**
* If applicable, add screenshots to help explain your problem.
![nothing](https://user-images.githubusercontent.com/90404314/132712518-849496b6-256e-4a8c-854f-c872418bbcbf.png)

[Log-2021-09-09-16-12.log](https://github.com/floh22/LeagueBroadcast/files/7137728/Log-2021-09-09-16-12.log)
[Crash-2021-09-09-16-14.log](https://github.com/floh22/LeagueBroadcast/files/7137729/Crash-2021-09-09-16-14.log)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1 19043.1165
[Log-2021-09-09-16-12.log](https://github.com/floh22/LeagueBroadcast/files/7137728/Log-2021-09-09-16-12.log)

**Additional context**
as soon as you start a custom champ select  nothing happens all blank after the champ select ends the app crashes and closes

**Comment by floh22** [comment]
Try restarting your league client and PC. Sometimes the client likes to freeze.

I can't reproduce this issue on my PC anymore, so I'm not sure if LeagueBroadcast is the issue or if its the client being weird. Does this happen consistently, or only sometimes?

**Comment by markos10l** [comment]
i tried restarting my pc but still nothing is shown ( sometimes the overlay of the champ select works ) i don't know why or how but sometimes very rare it works . i think the only solution for me now is to use an other overlay for the pick and ban phase and your  overlay for the in game . 
thank you for your time . i hope poeple wont get the same problems as me

**Comment by floh22** [comment]
try the newest release. If that doesn't fix it, open the console in your browser and send it, it may contain information about the nature of the issue.

**Comment by ihabdz55** [comment]
hey i download the new version and i did what you told
![this](https://user-images.githubusercontent.com/88833836/132747358-e935e60c-bc54-446b-b102-0fd08ac684ce.png)
 me . can you check the image and tell  me how to fix it plz

**Comment by markos10l** [comment]
i tryed the new release its seems like nothing in working in the champ select .
this is what i get in the console 
![it](https://user-images.githubusercontent.com/90404314/132770519-ab9595b3-db29-41b9-a918-41efe65000fc.png)
