### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by markos10l** [floh22/LeagueBroadcastHub#74]
![image](https://user-images.githubusercontent.com/90404314/132853547-947981fa-23db-4464-8a9c-a332787ec701.png)

i found the probleme of my pick and ban not working .  can you tell me please how to fix it ?

**Comment by markos10l** [comment]
![image](https://user-images.githubusercontent.com/90404314/132854732-ff576d5e-baf8-45f1-9c1e-772e20ef86f3.png)

**Comment by floh22** [comment]
The screenshots do not help much, though they do show the frontend getting updates. You can try opening the messages and seeing if you making changes in champ select shows up the messages. If they do show up, it may be an issue with the browser. If that is not the case, the issue may be with the client or the program
