### ISSUE TITLE
[BUG] on the gold chart

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#76]
bug in the gold chart, it only counts one side of the gold, and the font size of the chart does not increase.
can anyone help?, and would it be possible to change the graphic style? 

![image](https://user-images.githubusercontent.com/89580284/132905255-cb2aa29a-90f1-409e-bcd9-6d732a5ec2b2.png)

![image](https://user-images.githubusercontent.com/89580284/132905678-503cf912-27f7-454b-b8e1-bb21d0b15b30.png)

**Comment by FireFoXz09** [comment]
It counts only one side of the gold because the Red Team always had te lead, so it's normal! As for the graphic style, you can change the color and the size in the Ingame.json file.

**Comment by overkido** [comment]
I want to increase the font size, where it shows the gold of the bluside and the redside that is not changing the size I increase the graphic and the font is still msm size

**Comment by floh22** [comment]
You would have to change code and rebuilt the ingame frontend yourself.

I would start [here](https://github.com/floh22/LeagueBroadcast/blob/v2/Overlays/ingame/src/visual/GraphVisual.ts) in line 242 and onwards. The graph is made using [ChartJS](https://www.chartjs.org/) v.3.4.1
