### ISSUE TITLE
[BUG] Scoreboard stops reporting drakes after a game pause occurs

### ISSUE THREAD

**Issue by makermatic** [floh22/LeagueBroadcastHub#78]
**The bug**
During a tournament match, after a game goes into a pause, the scoreboard stops reporting drakes killed after the pause.

**To Reproduce**
1. Start a tournament lobby and game
2. Have one team capture at least one drake
3. Have one team pause the game for at least 5 minutes (or around that)
4. Unpause the game
5. Have one team capture the next incoming drake

**Comment by DaBenjamins** [comment]
I am experiencing this too

**Comment by floh22** [comment]
Im guessing this is due to the LiveEventAPI timing out and closing the socket after a period of inactivity. I'm not quite sure how to fix it atm. I don't know of a way to restart the socket while ingame, so it would require a game restart, which breaks everything else.

**Comment by iDanielWongi** [comment]
> Im guessing this is due to the LiveEventAPI timing out and closing the socket after a period of inactivity. I'm not quite sure how to fix it atm. I don't know of a way to restart the socket while ingame, so it would require a game restart, which breaks everything else.

It happens to me too, but now I get a message like that
https://i.imgur.com/vXkI8CM.png

**Comment by floh22** [comment]
> > Im guessing this is due to the LiveEventAPI timing out and closing the socket after a period of inactivity. I'm not quite sure how to fix it atm. I don't know of a way to restart the socket while ingame, so it would require a game restart, which breaks everything else.
> 
> It happens to me too, but now I get a message like that
> https://i.imgur.com/vXkI8CM.png

unrelated issue. This is caused by the league update and me having to update memory offsets. This happens every patch. sometimes im faster than other days to update, it might take up to 24 hours
