### ISSUE TITLE
LiveEventAPI Connection Failed

### ISSUE THREAD

**Issue by Ukan0** [floh22/LeagueBroadcastHub#8]
Hi. When i open a replay i get something like this in logs 
[12-23-25] [WARNING] Sequence contains no matching element
[12-23-26] [WARNING] Sequence contains no matching element
[12-23-26] [WARNING] Sequence contains no matching element
[12-23-26] LiveEventAPI Connection Failed!
[12-23-26] [WARNING] No connection could be made because the target machine actively refused it. 127.0.0.1:34243
I get the same logs on two different computers on different networks
Ive tried turning off firewall. Also checked if something is listening on the same port but i got nothing

**Comment by floh22** [comment]
Was this on patch 11.9 or 11.10?
Also can you post your lol game config? It should be in Riot Games/League of Legends/Config/game.cfg

**Comment by Ukan0** [comment]
I tested it yesterday on patch 11.9 and today on patch 11.10
[game.txt](https://github.com/floh22/LeagueBroadcastHub/files/6466606/game.txt)

**Comment by floh22** [comment]
Im guessing you do not have League installed at the default location. I haven't added support for this yet. For now if League is not installed at the default location, add the following to that file: 

```
[LiveEvents]
Enable=1
Port=34243
```

and drop the following file into the config folder as well and call it `LiveEvents.ini` . This should solve the LiveEvents issue.
https://github.com/floh22/LeagueBroadcastHub/files/6466833/LiveEvents.txt

**Comment by Ukan0** [comment]
Thank you. That helped
