### ISSUE TITLE
[BUG] Baron timer, elder timer, inhibitor timers is not showing

### ISSUE THREAD

**Issue by Nezumi2711** [floh22/LeagueBroadcastHub#83]
**Describe the bug**
Baron timer, elder timer, inhibitor timers is not showing.

**To Reproduce**
1. Open the League Broadcast.
2. Open LoL.
3. Go to spectator mode from list friend. (Not a custom game)
4. When connect in game, the League Broadcast still working, I turn on Scoreboard, Team Names, Item notifications,... is still show in http://localhost:9001/frontend?backend=localhost, but the baron timer, elder timer, inhibitor timers is not show anything in there.
So how can I resolve this problem? Thanks for read.
"I'm use Google Translate to write, I hope everyone can understand me. Thanks."
![image](https://user-images.githubusercontent.com/73208452/136681646-f9889e3b-ba8b-4826-9447-f4fda683fe6d.png)

**Comment by floh22** [comment]
The timers are named badly, and are the power play timers. Do these not show?

Inhibitor timers only show when an inhib is taken, this can be changed in config files

**Comment by Nezumi2711** [comment]
> The timers are named badly, and are the power play timers. Do these not show?
> 
> Inhibitor timers only show when an inhib is taken, this can be changed in config files

I'm not sure about this. When I turn on all them, the UI is doesn't change anything. It's like a photo. But what is the power play timers? Can you explain it?
_(The inhibitor times I will try again.)_
![image](https://user-images.githubusercontent.com/73208452/136720225-2c7a7be7-ff99-43ad-b24b-0368657dfea9.png)

**Comment by FireFoXz09** [comment]
The Baron and Elder Dragon "Power play" is a common term used in LoL esports to show the time and gold diff while a team have the Baron or the Elder Drake buff. It appear in the top corners only if a team have slain the monster.

Here a very quick screenshot how it works for the current Worlds 2021 of LoL : You have the Gold Difference (aka the power play) and the time remaining on the buff.

![image](https://user-images.githubusercontent.com/89284738/136828640-722f6247-e210-4f1f-b126-f4823b460636.png)

-----

If you want the esports timers to appear on the top of your screen, I would advise you to take a look on the wiki page of the spectator mode of League of Legends on how to edit your game files to have them : https://leagueoflegends.fandom.com/wiki/Spectator_Mode

_To turn the neutral timers into the dragon and baron timers used in pro play, open the game.cfg file in the **Riot Games > League Of Legends > Config** folder. Simply add "[Spectator] eSportsNeutralTimers=1" and when you enable the timers in spectate will appear as they do on the professional streams._

**Comment by Nezumi2711** [comment]
> The Baron and Elder Dragon "Power play" is a common term used in LoL esports to show the time and gold diff while a team have the Baron or the Elder Drake buff. It appear in the top corners only if a team have slain the monster.
> 
> Here a very quick screenshot how it works for the current Worlds 2021 of LoL : You have the Gold Difference (aka the power play) and the time remaining on the buff.
> 
> ![image](https://user-images.githubusercontent.com/89284738/136828640-722f6247-e210-4f1f-b126-f4823b460636.png)
> 
> If you want the esports timers to appear on the top of your screen, I would advise you to take a look on the wiki page of the spectator mode of League of Legends on how to edit your game files to have them : https://leagueoflegends.fandom.com/wiki/Spectator_Mode
> 
> _To turn the neutral timers into the dragon and baron timers used in pro play, open the game.cfg file in the **Riot Games > League Of Legends > Config** folder. Simply add "[Spectator] eSportsNeutralTimers=1" and when you enable the timers in spectate will appear as they do on the professional streams._

It's cool. Thanks a lot. I will try this. And I have one more question? How can I enable like this? _(I have draw a picture)_
![image](https://user-images.githubusercontent.com/73208452/136892157-a8236a52-f2aa-4ff8-8c6a-d77b3b2d69c6.png)

**Comment by FireFoXz09** [comment]
The Game Time + Dragon indicator for each team is already integrated in League Broadcast (and is also in the basic spectator HUD of the game). No need to do something. The dragons will appear when a team slay them.

**Comment by Nezumi2711** [comment]
Hmm... But I can't see them in League Broadcast. The inhibitor times is not show too (after inhibitor is taken) even though other feature is work correctly.  I have try again this recently.

**Comment by nicogigena** [comment]
HAVING SAME ISSUE! Only configured Inhib's one, not Elder and Baron's yer, but it appears for a fraction of second and makes transition Out instantly. Don´t know why, sometimes work sometimes not :c

**Comment by FireFoXz09** [comment]
Inhibitor is known to be buggy right now.  Use the false option to always see the inhibitors timers if you want to use them for now in the config file.
![image](https://user-images.githubusercontent.com/89284738/137047698-2948dd45-c0a1-4aaf-8b3f-d3e2f9e0f438.png)

**Comment by Nezumi2711** [comment]
How about the Dragon indicator? There is anyway to resolve it? I have try many times but it nothing changed.

**Comment by FireFoXz09** [comment]
The Dragon indicator? There's no dragon indicator for now. Only the Elder Dragon "Power Play" (samething as the Baron Power Play) is available (a timer that appear to let you know how much time is left on the buff for the team who have slain the Elder Drake)

**Comment by Nezumi2711** [comment]
Oh, so there is only a bug baron timer and elder timer. They are not showing after each team taken. There is anyway to fix?

**Comment by FireFoXz09** [comment]
It shows yes the dragon taken on the scoreboard. They will appear here when a team slay them. Run the League Broadcast a few times in spectator games to check how this interact :)
![image](https://user-images.githubusercontent.com/89284738/137242404-bbe98b38-b5d9-4beb-b6bd-96c243f34bc9.png)

**Comment by Nezumi2711** [comment]
Oh, ok. I will try. So and how about this, I meant is Elder Dragon "Power Play" and Baron "Power Play"?

> Oh, so there is only a bug baron timer and elder timer. They are not showing after each team taken. There is anyway to fix?

**Comment by overkido** [comment]
in mine it works perfectly, but the background of both the elder and the baron is one.

![image](https://user-images.githubusercontent.com/89580284/137409929-91b0055d-f491-4241-97a0-067136864e0b.png)

**Comment by Nezumi2711** [comment]
Ok, I think I have enough the way to resolve my problem. I will close issue now. Thanks everyone for help me.
