### ISSUE TITLE
[BUG] A white box is appear in HUD ingame

### ISSUE THREAD

**Issue by Nezumi2711** [floh22/LeagueBroadcastHub#84]
**Describe the bug**
A white box is appear in HUD in game and I don't know why.

**To Reproduce**
1. Open the League Broadcast.
2. Open LoL.
3. Go to spectator mode from list friend. (Not a custom game)
4. When connect ingame, the HUD of League Broadcast is work but it is appear the white box. I have this bug yesterday and don't know why its appear. The previous day is don't appear it.  I have try to turn off all features but it still there. Hope everyone help me to resolve it. Thanks.

![image](https://user-images.githubusercontent.com/73208452/137418857-23800ca6-6540-41f4-bdde-46d348d91697.png)

**Comment by Nezumi2711** [comment]
Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.

**Comment by leanbinh** [comment]
> Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.


hey, how can i use it in vietnam server i cant connect to leagueclient,
hope you will reply soon, thanks

**Comment by Nezumi2711** [comment]
> > Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.
> 
> hey, how can i use it in vietnam server i cant connect to leagueclient, hope you will reply soon, thanks

Bạn chỉ cần chạy với quyền admin là được nha.

**Comment by leanbinh** [comment]
> 

![image](https://user-images.githubusercontent.com/67872108/148050777-f6dc6ce8-6a2b-4be0-b301-2c0fad8c38e8.png)
nó bị kiểu này b ơi @@ mình đọc cái usage k hiểu cho lắm

**Comment by leanbinh** [comment]
> > > Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.
> > 
> > 
> > hey, how can i use it in vietnam server i cant connect to leagueclient, hope you will reply soon, thanks
> 
> Bạn chỉ cần chạy với quyền admin là được nha.

![image](https://user-images.githubusercontent.com/67872108/148050777-f6dc6ce8-6a2b-4be0-b301-2c0fad8c38e8.png)
nó bị kiểu này b ơi @@ mình đọc cái usage k hiểu cho lắm 

Hiện tại sv việt k cần phải run admin để connect tới lcu nữa rồi

**Comment by Nezumi2711** [comment]
> > > > Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.
> > > 
> > > 
> > > hey, how can i use it in vietnam server i cant connect to leagueclient, hope you will reply soon, thanks
> > 
> > 
> > Bạn chỉ cần chạy với quyền admin là được nha.
> 
> ![image](https://user-images.githubusercontent.com/67872108/148050777-f6dc6ce8-6a2b-4be0-b301-2c0fad8c38e8.png) nó bị kiểu này b ơi @@ mình đọc cái usage k hiểu cho lắm
> 
> Hiện tại sv việt k cần phải run admin để connect tới lcu nữa rồi

À, bạn cứ cancel là dùng bình thường nha. Khi vô chương trình ở góc phải bên trên có chữ client connect là được. Còn việc chạy quyền admin thì bên mình nếu k chạy sẽ bị crash, bên bạn thì k biết sao. :v

**Comment by leanbinh** [comment]
> > > > > Sorry, my bad. I have config gold graph wrong so I meet the error. I'm so sorry.
> > > > 
> > > > 
> > > > hey, how can i use it in vietnam server i cant connect to leagueclient, hope you will reply soon, thanks
> > > 
> > > 
> > > Bạn chỉ cần chạy với quyền admin là được nha.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/67872108/148050777-f6dc6ce8-6a2b-4be0-b301-2c0fad8c38e8.png) nó bị kiểu này b ơi @@ mình đọc cái usage k hiểu cho lắm
> > Hiện tại sv việt k cần phải run admin để connect tới lcu nữa rồi
> 
> À, bạn cứ cancel là dùng bình thường nha. Khi vô chương trình ở góc phải bên trên có chữ client connect là được. Còn việc chạy quyền admin thì bên mình nếu k chạy sẽ bị crash, bên bạn thì k biết sao. :v

hiện tại mình dùng được phần ingame rùi còn phần banpick mình test thử thì k thấy hoạt động, b có dùng được phần đó không ?

**Comment by Nezumi2711** [comment]
>hiện tại mình dùng được phần ingame rùi còn phần banpick mình test thử thì k thấy hoạt động, b có dùng được phần đó không ?

Mình dùng bình thường nha, bạn thử refresh cache ở phần mềm stream xem sao, hoặc bạn test trên trình duyệt thử (load lại trang nếu chưa thấy gì).

**Comment by leanbinh** [comment]
> > hiện tại mình dùng được phần ingame rùi còn phần banpick mình test thử thì k thấy hoạt động, b có dùng được phần đó không ?
> 
> Mình dùng bình thường nha, bạn thử refresh cache ở phần mềm stream xem sao, hoặc bạn test trên trình duyệt thử (load lại trang nếu chưa thấy gì).

![image](https://user-images.githubusercontent.com/67872108/148055679-899bb763-996c-4265-a530-724a98326560.png)
mình đã thử refresh rất nhiều lần nhưng màn hình vẫn trắng tinh tươm, không biết là do cái gì nữa :((

**Comment by Nezumi2711** [comment]
> 
> ![image](https://user-images.githubusercontent.com/67872108/148055679-899bb763-996c-4265-a530-724a98326560.png) mình đã thử refresh rất nhiều lần nhưng màn hình vẫn trắng tinh tươm, không biết là do cái gì nữa :((

Bạn add bot vô là nó k đọc được nha bạn, nếu bạn muốn test thì tạo trận đấu giải, 1 mình bạn trong room đó cũng được và test thử.

**Comment by leanbinh** [comment]
> > ![image](https://user-images.githubusercontent.com/67872108/148055679-899bb763-996c-4265-a530-724a98326560.png) mình đã thử refresh rất nhiều lần nhưng màn hình vẫn trắng tinh tươm, không biết là do cái gì nữa :((
> 
> Bạn add bot vô là nó k đọc được nha bạn, nếu bạn muốn test thì tạo trận đấu giải, 1 mình bạn trong room đó cũng được và test thử.

![image](https://user-images.githubusercontent.com/67872108/148056402-9a534239-39a7-49aa-89a3-8349074a7838.png)
mình cũng đã thử hết nhưng kết quả trả lại bằng 0 chắc mình sẽ thử lại bên cái máy thứ 2 xem có bị như thế nữa không

**Comment by leanbinh** [comment]
> 
> Bạn add bot vô là nó k đọc được nha bạn, nếu bạn muốn test thì tạo trận đấu giải, 1 mình bạn trong room đó cũng được và test thử.

khi sang máy thứ 2 thì mọi thứ lại hoạt động bình thường, có vẻ máy chính của mình đang gặp chút trục trặc gì đó, cảm ơn bạn đã giúp đỡ mình nhiều

**Comment by Nezumi2711** [comment]
> khi sang máy thứ 2 thì mọi thứ lại hoạt động bình thường, có vẻ máy chính của mình đang gặp chút trục trặc gì đó, cảm ơn bạn đã giúp đỡ mình nhiều

Ok bạn.
