### ISSUE TITLE
[BUG] Change the logo on Pick Ban

### ISSUE THREAD

**Issue by fsqBr** [floh22/LeagueBroadcastHub#87]
Hi, 
I tried to change de logo who stay on bottom of the screen , changed the the image on path Frontend\pickban\static\media\scuffed.2fe400e4.png, but without a sucess, there is orther way to do this?

**Comment by floh22** [comment]
This is the correct way, but you need to restart the program for this to take effect

**Comment by Taku092** [comment]
Hey i restarted the Programm and changed the path but its still not working
