### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#88]
will the update of drags and new items take time?

![image](https://user-images.githubusercontent.com/89580284/142738947-b4015be7-8a18-4046-b418-6d3036c9ec1f.png)
![image](https://user-images.githubusercontent.com/89580284/142738971-959dde51-71f3-4da1-819d-aae10db30c6d.png)

**Comment by OrionCodeDev** [comment]
+1

**Comment by FireFoXz09** [comment]
The new items "seems" to already work with the actual system (since it get's the info directly from the game I guess). I've not tested it with ALL of them but the few I saw worked like the actual items.

For the 2 new dragons tho, yes it would be a nice update to add ASAP.

**Comment by floh22** [comment]
Fixed in [latest release](https://github.com/floh22/LeagueBroadcast/releases/tag/v1.4.106)

**Comment by floh22** [comment]
Side note, I made the icons for the two new dragons myself. They are probably not perfect, but client files did not include icons in the same style/resolution as the old ones. If anyone has better options, feel free to create a Pull request
