### ISSUE TITLE
[BUG] No ScoreBoardPopUps for the new Hextech/Chemtech dragons

### ISSUE THREAD

**Issue by FireFoXz09** [floh22/LeagueBroadcastHub#89]
Missing folders for the scoreboardPopUps when the new dragon type spawns or gets killed. I dunno if it is created or programmed in the code yet (I haven't seen it in the config/Ingame.json). It did nothing on my side when i tested it a few minutes ago.

Folder :
LeagueBroadcast-1.4.106\Frontend\ingame\images\scoreboardPopUps

Missing the Hextech type and the Chemtech type.

**Comment by floh22** [comment]
Until I have time to fix it, add the corresponding folders and files to the overlay files.
This means you have to add the folders `Hextech` and `Chemtech` to `Frontend/ingame/images/scoreboardPopUps/Dragon` and then add the corresponding files as well. 

Edit: Fixed folder location

**Comment by FireFoXz09** [comment]
If I just need to add the folders and pictures/video like for the same dragons, I can do that ;) I'll try it and let you know if this works!

**Comment by shinilee** [comment]
> 

I just did but it only work for kill spwan doesn't work for me for the new dragons old dragon still popup for spawn but new dragon doesn't work but it work for kill popup for the new dragon

for popup I use video for kill I use image

FireFoXz09 let me know if your test

**Comment by FireFoXz09** [comment]
The popups works for the kills of the new dragons (I dunno for the spawn since I never use them, I'll try later this week), but the icon in the scoreboard the the chemtech or hextech dragons won't load. (it puts the blacksquare with a green bar like if they can't find the picture)

![Screenshot 2021-11-22 18-32-29](https://user-images.githubusercontent.com/89284738/142950447-35639162-5941-4d61-be8a-496cf52511e7.png)

**Comment by shinilee** [comment]
mine working fine for score display dragon it just spwan not working for me

**Comment by floh22** [comment]
Try deleting the Frontend folder and then replacing it again, it might be possible that the update failed to overwrite the old files it needed to.
Make sure `Frontend/ingame/images/dragons` contains both `chemtechLarge.png` and `hextechLarge.png`

As for the popups, the folder location i wrote was missing the last component, make sure to add the new folders inside the `Dragon` folder

**Comment by shinilee** [comment]
> Try deleting the Frontend folder and then replacing it again, it might be possible that the update failed to overwrite the old files it needed to. Make sure `Frontend/ingame/images/dragons` contains both `chemtechLarge.png` and `hextechLarge.png`
> 
> As for the popups, the folder location i wrote was missing the last component, make sure to add the new folders inside the `Dragon` folder

![image](https://user-images.githubusercontent.com/82671596/143042565-f2e933c5-e562-4fb3-9b56-e8aa9fbb2a41.png)

this is my setup but you saying I have make another dragon fonder and put Chemtech, Hextech in to that folder?

**Comment by overkido** [comment]
How do you add an image to the background of the inhibitors, in my one, it bugs and the image does not appear in the background?

![image](https://user-images.githubusercontent.com/89580284/143042417-9007f19c-53b5-42ae-b8aa-6bffc7eb6131.png)

How do I put the drag folders and images when it is killed?

![image](https://user-images.githubusercontent.com/89580284/143042474-f416cf74-a491-49f6-be55-c78e41d5454c.png)

**Comment by shinilee** [comment]
I just tried to add another dragon folder in the dragon folder and it didn't work and now kill popup doesn't even working

![image](https://user-images.githubusercontent.com/82671596/143044342-37cad356-c532-4061-bac5-6f9275844dcd.png)

**Comment by overkido** [comment]
taking advantage, would it be possible to remove the client's timer to add to the program's hub?, like in the world and msi, that the herald drags and fine baron timers in the program's hub?

![image](https://user-images.githubusercontent.com/89580284/143044476-6902b237-923c-472b-b795-194d75757b2f.png)

**Comment by overkido** [comment]
even to be able to customize it would be better for the people who make the championships.

the showlogo of drags and baron doesn't work either, i've activated it, but when drag or baron kills it doesn't show the logo of the team that made it. 
 
> ![imagem](https://user-images.githubusercontent.com/89580284/143044476-6902b237-923c-472b-b795-194d75757b2f.png)

**Comment by overkido** [comment]
does anyone know where i change the video file format from mp4 to mov? I've looked for it, I haven't found it.

**Comment by shinilee** [comment]
![image](https://user-images.githubusercontent.com/82671596/143047753-c70272dd-d580-4297-8504-46ed10f386e7.png)

the new dragon popup working after 2nd one 1st dragon doesn't popup for the newdragon

1. Firedragon popup work
2. Mountain dragon popup work
3. chemtech dragon popup not work
4. chemtech dragon popup work
5. chemtech dragon popup work

I think it's bug

**Comment by floh22** [comment]
> > Try deleting the Frontend folder and then replacing it again, it might be possible that the update failed to overwrite the old files it needed to. Make sure `Frontend/ingame/images/dragons` contains both `chemtechLarge.png` and `hextechLarge.png`
> > As for the popups, the folder location i wrote was missing the last component, make sure to add the new folders inside the `Dragon` folder
> 
> ![image](https://user-images.githubusercontent.com/82671596/143042565-f2e933c5-e562-4fb3-9b56-e8aa9fbb2a41.png)
> 
> this is my setup but you saying I have make another dragon fonder and put Chemtech, Hextech in to that folder?

This is correct. I will add missing files at some point in the future when I have access to my workstation again.

**Comment by floh22** [comment]
As for the rest of this issue, this is not a support thread. If you have an issue, please open a separate issue for the topic and make sure your issue is not a duplicate of an existing one.

Custom timers are not supported as of this moment and only .mp4 files are supported. If you have .movs, convert them.

**Comment by shinilee** [comment]
> ![image](https://user-images.githubusercontent.com/82671596/143047753-c70272dd-d580-4297-8504-46ed10f386e7.png)
> 
> the new dragon popup working after 2nd one 1st dragon doesn't popup for the newdragon
> 
> 1. Firedragon popup work
> 2. Mountain dragon popup work
> 3. chemtech dragon popup not work
> 4. chemtech dragon popup work
> 5. chemtech dragon popup work
> 
> I think it's bug

I just test run again and it's working now the new dragon popup working without any problem I think it's just glitch 

https://youtu.be/1B8o-DXFJsU

**Comment by FireFoXz09** [comment]
> How do you add an image to the background of the inhibitors, in my one, it bugs and the image does not appear in the background?
> 
> ![image](https://user-images.githubusercontent.com/89580284/143042417-9007f19c-53b5-42ae-b8aa-6bffc7eb6131.png)
> 
> How do I put the drag folders and images when it is killed?
> 
> ![image](https://user-images.githubusercontent.com/89580284/143042474-f416cf74-a491-49f6-be55-c78e41d5454c.png)

The inhibitor countdown don't have a background image cause I had the same issue, it bugged. I just made this in my in-game overlay and put the inhibitor timer above it.

**Comment by overkido** [comment]
no caso vc fez uma arte base e jogo o link por cima sem o alfa do inibidor e sem imagem ?

**Comment by overkido** [comment]
Eu tentei colocar o redside do outro lado do mapa, encima do mini-mapa mas não consegui, ai deixei assim tbm, queria por redside no outro lado e assim ter mais espaço pra personalizar mas não funcionou.

**Comment by FireFoXz09** [comment]
I solved the problem for the dragon icon in the score on the top of the overlay. I did a bad copy-paste of the CONFIF files from my old setup to the new version. Everything works as planned!  :)
