### ISSUE TITLE
[DrakeSoulPoint] what is this mean?

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#91]
I though soul point will popup on after 2nd drake killed but it appear at when blue and red team have 3 drake each 
like when red team got 3 drake and blue team got 2 drake and when blue team killed another drake then the soulpoint popup is this normal?

**Comment by overkido** [comment]
não precisa ambos os times ter drakes, ex: time azul tem 2 drakes feitos e fez o 3º dragão o time azul entra em soulpoint pq falta 1 drag para fechar a alma.

**Comment by FireFoXz09** [comment]
The LeagueBroadcast was build to announce that the next dragon is a "possible" dragon soul, not an actual "dragon soul acquired" pop-up. If I understood you correctly...

**Comment by shinilee** [comment]
> The LeagueBroadcast was build to announce that the next dragon is a "possible" dragon soul, not an actual "dragon soul acquired" pop-up. If I understood you correctly...

but I don't understand why it only popup at 6th dragon? like when blue team slay 3rd dragon it didn't popup but when blue team have 3 dragon and red team slay 3rd dragon it popup

**Comment by FireFoXz09** [comment]
I dunno, this is strange. Maybe a bug with the new dragons type? I don't use the Soul Point system since it does not bring the information I want to share while I cast (I just say it out loud) so I don't really know what is happenning.

**Comment by floh22** [comment]
The soul point pop up is to announce that the next dragon is a possible soul for the team with 3 dragons. This was a feature request quite some time ago, and implemented rather poorly. Future changes will improve clarity on this.
