### ISSUE TITLE
add feature please [FEATURE]

### ISSUE THREAD

**Issue by overkido** [floh22/LeagueBroadcastHub#93]
would it be possible to add the gold advantage of the team that is behind in the match? 

![image](https://user-images.githubusercontent.com/89580284/143304177-926c4c9b-5c33-4c9b-b3ee-a78ad40bbaa6.png)

**Comment by FireFoXz09** [comment]
Ohhh the new bounty feature. Interesting...

**Comment by overkido** [comment]
> Ohhh, o novo recurso de recompensa. Interessante...

exatamente!

**Comment by floh22** [comment]
Doesn't look like I can get this information from memory easily without actually having the UI open, so this wont get added
