### ISSUE TITLE
[BUG] Crash on gold graph display and/or item complete

### ISSUE THREAD

**Issue by VermilionRose** [floh22/LeagueBroadcastHub#94]
**Describe the bug**
Running ingame graphic through LeagueBroadcast.
Displaying timer, kills, towers, gold, and dragons correctly in a custom InGame.config file.
Made to display gold graph (not the gold tab). Shows for a few seconds and then the entire program crashed.
This did coincide with a completed item from one of the players triggering the relevant graphic according to the log file so I'm not sure. (A red/Chaos team Nocturne built an Eclipse just before I clicked the gold graph button.)
20:40 is approximate game start according to the log file

**To Reproduce**
1. Start League of Legends
2. Start League Broadcast in Admin mode
3. Start Champ Select (pick-ban works fine)
4. Start game and ingame.config and display work as intended
5. Show gold tab multiple times
6. Unable to replicate the behavior on a different machine

**Expected behavior**

**Material**
[Twitch Vod of the App crashing](https://www.twitch.tv/videos/1219638078)
App crashes at around ~2:59:40. Nocturne completes the item. Gold graph is shown, and the app visibly crashes. 
[Log-2021-11-29-19-59.log](https://github.com/floh22/LeagueBroadcast/files/7622773/Log-2021-11-29-19-59.log)
[Crash-2021-11-29-21-50.log](https://github.com/floh22/LeagueBroadcast/files/7622774/Crash-2021-11-29-21-50.log)
Will attempt to get a replay file from one of the players

**Desktop (please complete the following information):**
-- System Details -- 
League Broadcast Version: 1.4.106.21326
OS: Win 10 2009

**Additional context**

**Comment by FireFoXz09** [comment]
Had the same problem / crash yesterday! Gold graph + an item appearing = crash. Maybe it's unrelated but it's the same condition...

At 2:19:20 in the video
https://www.twitch.tv/videos/1220093983

**Comment by floh22** [comment]
This happened while the game was running? The Crash log would indicate that this should happen at the beginning of the game, and even then, only when Riot servers send an invalid response or no response at all

**Comment by FireFoXz09** [comment]
Happened again this monday.

In both situation, the activation of the graph make League Broadcast crash IF we are past the **35 minute mark.**

VOD : https://www.twitch.tv/videos/1305923143
1:07:25 in the video
