### ISSUE TITLE
[FEATURE] Build not working, /frontend missing

### ISSUE THREAD

**Issue by LeBraveLittleToaster** [floh22/LeagueBroadcastHub#95]
**Describe the bug**
When compiling your project everything works as expected, but if you access overlay from the browser, he reports a 404 /frontend not found. From my observation, the frontend folder is not copied to the compiled folder. If you manually copy the files from the release, you get a 401 Unauthorized.

**To Reproduce**
See text in description

**Expected behavior**
A build script that compiles everything and copies over the needed html/js files.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 10.0.19043 Build 19043

**Additional context**
Currently trying to extend your work on GlobalHotkeys (latest fork)

**Comment by FireFoXz09** [comment]
Do you use thoses browser links to see the overlays?

This one http://localhost:9001/frontend?backend=localhost as a browser source in OBS in your ingame scene
and http://localhost:9001/?backend=ws://localhost:9001/api as a browser source in OBS in your PickBan scene

**Comment by floh22** [comment]
For clarity sake:

A build script is included, will build and bundle everything after Publishing.
To do so, both a `Publish` and `Releases` folder must be present in the Root folder.

Currently the ingame frontend is rather outdated, and the user must explicitly use parcel@1.12.3, as parcel@2.x.x introduces breaking changes that I have not yet made. Though of course this can be updated with a bit of work.

Other than that, the project currently uses an extremely janky combination of .NET Core 3.1 and C# 9. So when building, its recommended to just update to either .NET 5 or .NET 6.

I will have to update and include proper build instructions in this repo at some point, but until that point, this issue should hopefully help anyone trying to build it themselves
