### ISSUE TITLE
the new drakes are shown on the scoreboard but when they spawn or get killed they don't show like the other drakes 

### ISSUE THREAD

**Issue by kaminari1898** [floh22/LeagueBroadcastHub#96]
title  + ( im not good at coding that's why i'm asking if you kindly can add them ) thank you

**Comment by shinilee** [comment]
#89 check this post

**Comment by kaminari1898** [comment]
> #89 check this post

ok thank you i will try

**Comment by kaminari1898** [comment]
thank you for the help it worked  :)
