### ISSUE TITLE
How do I even run this? 

### ISSUE THREAD

**Issue by hldup** [floh22/LeagueBroadcastHub#97]
Got no idea, my school is having a league tournament between classes, I'm trying to make the most out of it

**Comment by FireFoXz09** [comment]
All the instructions are in the README.md file (or on the main page of this program)

You don't need the LeagueBroadcast tool to "run" the tournament. This is only a software to help you make your streaming looking more like the professionnal league production (like the LCS/LCK/LEC/etc.). You need to have a basic understanding of streaming, OBS Studio (or any other streaming software you like) and I guess how to edit files/parameters in NotePad.

Now, if you WANT to use it, it's pretty simple and sel explanatory in the README file like I said. You launch the program, spectate a LoL game, put the links in your browser/OBS and tadam, the overlay is over your game and gives you tons of information. You also need to design your own pictures to make it more like you want, but the basic stuff into it shoud do the trick so you can understand how it works.

**Comment by hldup** [comment]
Sorry, I was just retarded. Downloaded the sourcecode for some reason. Tho now i just get 404. It says its connected, and is displaying players name. Any ideas?
