### ISSUE TITLE
[BUG] Race condition when updating offsets before the first game

### ISSUE THREAD

**Issue by Russeus** [floh22/LeagueBroadcastHub#98]
**Describe the bug**
LeagueBroadcast can't read all champion data from memory. It happens with any Spectate game.

**How To Reproduce**
1. Spectate a game.
2. Open LeagueBroadcast.
3. Get error (see image).

**Expected behavior**
LeagueBroadcast read champion data and shows Gold per Minute and other data without problems.

**Material**
![error](https://user-images.githubusercontent.com/89173918/145269242-fff7208e-00c0-4035-9be2-880f369a22cf.png)
[Log-2021-12-08-15-08.log](https://github.com/floh22/LeagueBroadcast/files/7678302/Log-2021-12-08-15-08.log)

**Desktop:**
 - OS: Windows 10 Home
 - Version 21H1

**Additional context**
I edited the server from the Component.json file to "las".

**Comment by OrionCodeDev** [comment]
Hey, you must wait until @floh22 will update offsets. Regards

**Comment by floh22** [comment]
<del>Offsets for 11.24.1 are in the repo, they should be updated. <del>

<del>Is anyone else having issues?<del>

**Comment by floh22** [comment]
Looking at the logs again this might have been an unlucky case of github being slow/ slow download. Either way, good to know that a race condition exists when updating offsets and starting the first game after a patch or new installation

**Comment by OrionCodeDev** [comment]
Clear installation, still same error with LiveEvents and EnableReplay in config :/ what;s the problem
[Log-2021-12-11-13-59.log](https://github.com/floh22/LeagueBroadcast/files/7697045/Log-2021-12-11-13-59.log)
?

**Comment by floh22** [comment]
Looks like it wasnt a race condition, but just incorrect offsets. Closing after updated offset was published
