### ISSUE TITLE
I edited component. json as instructed, but it doesn't look right 

### ISSUE THREAD

**Issue by Khhd1** [floh22/LeagueBroadcastHub#99]
![1](https://user-images.githubusercontent.com/82941693/145555027-bfff1139-536f-44ae-9af1-8e3cf30bce30.jpg)
![2](https://user-images.githubusercontent.com/82941693/145555036-16628d3c-7f74-4623-8386-e1703e3f2664.jpg)
![3](https://user-images.githubusercontent.com/82941693/145555038-6b668d1c-56f8-44aa-84e5-574c2a470a38.jpg)

**Comment by Khhd1** [comment]
![image](https://user-images.githubusercontent.com/82941693/145561532-1078bc14-4f4a-4982-a1e3-949607832eae.png)
![image](https://user-images.githubusercontent.com/82941693/145561676-aa49daa0-4fc2-45c1-bcec-e252e9213d6c.png)
The above problem was solved, but... This issue has cropped up again and I have updated Farsight

**Comment by Khhd1** [comment]
![image](https://user-images.githubusercontent.com/82941693/145561809-6ff3b9ae-69de-4446-b802-34f4a4d8f6a9.png)

**Comment by Khhd1** [comment]
[Log-2021-12-10-18-29.log](https://github.com/floh22/LeagueBroadcast/files/7692123/Log-2021-12-10-18-29.log)

**Comment by socktow** [comment]
try : 
F:\LOL\Riot Games\League of Legends 
![image](https://user-images.githubusercontent.com/14296959/145672212-3233c9e0-1cf8-4927-95cf-fbe7559e95ef.png)

**Comment by JIANYU77I** [comment]
> 试试： F:\LOL\Riot Games\英雄联盟 ![图片](https://user-images.githubusercontent.com/14296959/145672212-3233c9e0-1cf8-4927-95cf-fbe7559e95ef.png)

Yes, I'm done with the game path problem

**Comment by Khhd1** [comment]
> try : F:\LOL\Riot Games\League of Legends ![image](https://user-images.githubusercontent.com/14296959/145672212-3233c9e0-1cf8-4927-95cf-fbe7559e95ef.png)

Yes, I'm done with the game path problem.

**Comment by JIANYU77I** [comment]
:)But my current question is:could not read all champion data form memory

**Comment by Khhd1** [comment]
:)But my current question :could not read all champion data form memory

**Comment by socktow** [comment]
ya because now patch is 11.24.4 not 11.24.1 
maybe it will be fixed in 11.25 , i think so
![image](https://user-images.githubusercontent.com/14296959/145713622-bbb64543-4ee6-4db8-9a00-504e38243f17.png)

**Comment by overkido** [comment]
nada de resolver o bug?

**Comment by OrionCodeDev** [comment]
Resolved by new Offsets:

"Manager": "0x186CD64",
```
{
  "GameVersion": "11.24.1",
  "GameOffsets": {
    "Manager": "0x186CD64",
    "MapCount": "0x2c",
    "MapRoot": "0x28",
    "MapNodeNetId": "0x10",
    "MapNodeObject": "0x14"
  },
  "ObjectOffsets": {
    "ID": "0x20",
    "NetworkID": "0xcc",
    "Team": "0x4c",
    "Pos": "0xF0",
    "Mana": "0x2B4",
    "MaxMana": "0x2C4",
    "Health": "0xDB4",
    "MaxHealth": "0xDC4",
    "CurrentGold": "0x1B98",
    "GoldTotal": "0x1BA8",
    "EXP": "0x3384",
    "Name": "0x2BDC",
    "ItemList": "0x0",
    "SpellBook": "0x0",
    "ItemListItem": "0x0",
    "ItemInfo": "0x0",
    "ItemInfoId": "0x0"
  },
  "FileVersion": "1.0"
}
```

**Comment by Khhd1** [comment]
> 



> Resolved by new Offsets:
> 
> "Manager": "0x186CD64",
> 
> ```
> {
>   "GameVersion": "11.24.1",
>   "GameOffsets": {
>     "Manager": "0x186CD64",
>     "MapCount": "0x2c",
>     "MapRoot": "0x28",
>     "MapNodeNetId": "0x10",
>     "MapNodeObject": "0x14"
>   },
>   "ObjectOffsets": {
>     "ID": "0x20",
>     "NetworkID": "0xcc",
>     "Team": "0x4c",
>     "Pos": "0xF0",
>     "Mana": "0x2B4",
>     "MaxMana": "0x2C4",
>     "Health": "0xDB4",
>     "MaxHealth": "0xDC4",
>     "CurrentGold": "0x1B98",
>     "GoldTotal": "0x1BA8",
>     "EXP": "0x3384",
>     "Name": "0x2BDC",
>     "ItemList": "0x0",
>     "SpellBook": "0x0",
>     "ItemListItem": "0x0",
>     "ItemInfo": "0x0",
>     "ItemInfoId": "0x0"
>   },
>   "FileVersion": "1.0"
> }
> ```

Oh! Thank you. I successfully solved the problem!

**Comment by floh22** [comment]
For others facing a similar issue before Season 12 begins: Delete Farsight.json and restart the program. Riot changed internal structures and I did not notice, leading to me publishing incorrect offsets.
